grafana/cog

internal/ast/compiler/compiler.go
internal/ast/compiler/googlecloudmonitoring.go

`googlecloudmonitoring` schemas before 10.2.x define a disjunction that cog can't handle (it doesn't have a clear discriminator that can be used).
To be able to generate code for versions <10.2.x, I introduced a compiler pass to alter the schema in a way that mimics the changes that were introduced in 10.2.x.
See the comment on the compiler pass for more details on the changes made to google cloud monitoring schemas.
Note: this PR should allow us to generate and release types + builders for Grafana v10.1.x in addition to the already published code for v10.2.x

Add a compiler pass to make <10.2.x versions of the googlecloudmonitoring schemas parseable

---

config/dashboard.variables.veneers.common.yaml
examples/_go/main.go
examples/typescript/index.ts
internal/ast/builder.go
internal/ast/types.go
internal/jennies/golang/builder.go
internal/jennies/typescript/builder.go
internal/jennies/typescript/index.go
internal/jennies/typescript/rawtypes.go
internal/jennies/typescript/templates/builder.tmpl
internal/jennies/typescript/tmpl.go
internal/jennies/typescript/types.go
internal/veneers/builder/rules.go
internal/veneers/builder/rules_test.go
internal/veneers/builder/selectors.go
internal/veneers/builder/selectors_test.go
internal/veneers/option/actions.go
internal/veneers/option/selectors.go
internal/veneers/option/selectors_test.go
internal/veneers/rewrite/rewrite_test.go
internal/veneers/yaml/builder.go
internal/veneers/yaml/option.go
internal/veneers/yaml/veneers.go
testdata/jennies/builders/composable_slot/test.txtar
testdata/jennies/builders/constructor_initializations/test.txtar
testdata/jennies/builders/dataquery_variant_builder/test.txtar
testdata/jennies/builders/foreign_builder/test.txtar
testdata/jennies/rawtypes/enums.txtar

This PR configures a few veneers to improve the API around dashboard variables.
These variables are described by a single model in the schemas, even though different variable types actually use a subset of the fields in that model.
I use veneers to generate a builder per variable type exposed by the schema, and I restrict the options generated for each builder to what Grafana allows us to configure.

Define veneers for dashboard variables

---

config/dashboard.veneers.common.yaml
internal/veneers/builder/rules.go

This veener needs to gracefully handle schemas with more types than just Options/FieldConfig.
Fixes #198

Fix Panel composition veneer

---

config/heatmap.veneers.common.yaml
internal/veneers/option/actions.go
internal/veneers/option/selectors.go
internal/veneers/option/selectors_test.go

Because of a slight misconfiguration, veneers configured for the Heatmap panel were not applied. This PR fixes that and makes the `by_builder` selector behave in a more intuitive way.

Fix configuration and execution of heatmap-related veneers

---

config/dashboard.veneers.common.yaml
config/dashboard.veneers.go.yaml
examples/typescript/disk.ts
internal/jennies/typescript/builder.go
internal/jennies/typescript/templates/builder.tmpl
internal/txtartest/txtar.go
testdata/jennies/builders/array_append/test.txtar
testdata/jennies/builders/envelope_assignment/test.txtar
testdata/jennies/builders/known_any/test.txtar
testdata/jennies/builders/struct_fields_as_args_assignment/test.txtar

Fixes https://github.com/grafana/grafana-foundation-sdk/issues/18
This problem was caused by a two issues that this PR addresses:
* "*envelope assignments*" were not supported in Typescript. ie: cog didn't generate any code for them.
* a global veneer was applied to `panel.withOverride` but should have been applied to Go only.
ToDo:

Support envelope assignments in Typescript

---

.github/workflows/ci.yaml
internal/jennies/typescript/rawtypes.go
internal/jennies/typescript/types.go
testdata/jennies/builders/initialization_safeguards/test.txtar

I noticed that some initialization safeguards in typescript could be generated incorrectly:
```typescript
this.internal.options.legend = map[string]interface {}{"show":true};
```
This PR addresses that.
ToDo:

Fix map values formatting for initialization safeguards in builders

---

internal/jsonschema/generator.go
internal/jsonschema/generator_test.go
internal/jsonschema/utils.go

The parser we use for jsonschema returns `json.Number` instances for numeric enum values. This can be a problem since jennies expect scalar Go values when doing the codegen.
This PR unwraps these values before injecting them into the IR.

Correctly parse enum values in jsonschema

---

internal/jsonschema/generator.go
testdata/jsonschema/consts/GenerateAST/ir.json
testdata/jsonschema/consts/schema.json

While playing with JSONSchemas generated from typescript models in grafana/grafana, I encountered a bug caused by constants that were incorrectly parsed.
Our parser was correct for untyped `const` definitions, but not typed ones. This PR addresses this issue.

Fix incorrect typed vs untyped constant parsing in jsonschema

---

internal/ast/compiler/disjunctions.go
internal/ast/compiler/disjunctions_infer_mapping.go
internal/ast/compiler/disjunctions_infer_mapping_test.go
internal/ast/compiler/disjunctions_test.go
internal/jennies/golang/jennies.go
internal/jennies/java/jennies.go
internal/jennies/python/jennies.go

This PR splits the `DisjunctionToType` compiler pass even further, isolating the code responsible for inferring the discriminator field and mapping to use in its own pass.
I am doing this for two reasons:
* to make these passes less hard to read and understand
* to enable unmarshalling from JSON easier in languages like Python that support disjunctions but still need to know the discriminator & mapping to unmarshal correctly
Note: this PR doesn't change the code generated by cog

Split the disjunction discriminator and mapping inference code in a standalone compiler pass

---

internal/jennies/golang/builder.go
internal/jennies/golang/imports.go
internal/jennies/golang/jsonmarshalling.go
internal/jennies/golang/rawtypes.go
internal/jennies/golang/templates/builders/builder.tmpl
internal/jennies/golang/templates/runtime/variant_plugins.tmpl
internal/jennies/golang/tmpl.go
internal/jennies/golang/types.go
internal/jennies/golang/variantsplugins.go
testdata/jennies/builders/package-with-dashes/GoBuilder/builderpkg/somenicebuilder_builder_gen.go
testdata/jennies/builders/package-with-dashes/PythonBuilder/builders/builder-pkg.py
testdata/jennies/builders/package-with-dashes/TypescriptBuilder/src/builder-pkg/somenicebuilder_builder_gen.ts
testdata/jennies/builders/package-with-dashes/builders_context.json
testdata/jennies/rawtypes/intersections/GoRawTypes/intersections/types_gen.go
testdata/jennies/rawtypes/package-with-dashes/GoJSONMarshalling/withdashes/types_json_marshalling_gen.go
testdata/jennies/rawtypes/package-with-dashes/GoRawTypes/withdashes/types_gen.go
testdata/jennies/rawtypes/package-with-dashes/JavaRawTypes/with-dashes/RefreshRate.java
testdata/jennies/rawtypes/package-with-dashes/JavaRawTypes/with-dashes/SomeStruct.java
testdata/jennies/rawtypes/package-with-dashes/JavaRawTypes/with-dashes/StringOrBool.java
testdata/jennies/rawtypes/package-with-dashes/PythonRawTypes/models/with-dashes.py
testdata/jennies/rawtypes/package-with-dashes/TypescriptRawTypes/src/with-dashes/types_gen.ts
testdata/jennies/rawtypes/package-with-dashes/ir.json

Our jennies do not sanitize package names enough, so if a package contains dashes it will be rendered as-is in the generated code, which is a problem for most languages.
Starting with Go, let's fix that!

Support packages with dashes in Go

---

config/dashboard.veneers.common.yaml

```go
Link(
dashboard.NewDashboardLinkBuilder("Grafana Agent Dashboards").
Type(dashboard.DashboardLinkTypeDashboards).
Icon("external link").
IncludeVars(true).
KeepTime(true).
Tags([]string{"grafana-agent-integration"}),
).
```
Instead of:
```go
Links([]cog.Builder[dashboard.DashboardLink]{
dashboard.NewDashboardLinkBuilder().
Type(dashboard.DashboardLinkTypeDashboards).
Title("Grafana Agent Dashboards").
Icon("external link").
IncludeVars(true).
KeepTime(true).
Tags([]string{"grafana-agent-integration"}),
}).
```

Define a few veneers to make defining dashboard links easier

---

internal/ast/compiler/compiler.go
internal/ast/compiler/constants.go
internal/ast/compiler/prometheusdataquery.go
internal/ast/types.go

Relates to https://github.com/grafana/grafana-foundation-sdk/issues/36
The CUE schema doesn't contain this field, so until it's updated we can *artificially* define it with a compiler pass.
Cf grafana/grafana for its definition: https://github.com/grafana/grafana/blob/9c0501a1674ba66169e082984f36534427a0eaf8/public/app/plugins/datasource/prometheus/types.ts#L16

Add missing "interval" field in prometheus dataquery

---

cmd/cli/generate/command.go
cmd/cli/inspect/command.go
cmd/cli/loaders/cue.go
cmd/cli/loaders/jsonregistry.go
cmd/cli/loaders/jsonschema.go
cmd/cli/loaders/kindregistry.go
cmd/cli/loaders/kindsyscomposable.go
cmd/cli/loaders/kindsyscore.go
cmd/cli/loaders/kindsyscustom.go
cmd/cli/loaders/openapi.go
cmd/cli/loaders/options.go
internal/ast/schema.go
internal/ast/types.go

In the context of https://github.com/grafana/cog/issues/71, I'm generating JSON schemas for a lot of types defined in grafana/grafana.
To be able to use these schemas with cog, I am relying on a "jsonschema registry" loader that this PR introduces.
It's not meant to stay in the codebase forever since we don't have a clear path forward on how schemas will be defined and where they'll be published, but this loader can at least be useful in the context of #71

Jsonschema registry

---

internal/jennies/golang/jsonmarshalling.go
internal/jennies/golang/rawtypes.go
internal/jennies/golang/types.go
internal/jennies/typescript/rawtypes.go
internal/jennies/typescript/types.go
testdata/jennies/rawtypes/struct_with_complex_fields/GoRawTypes/struct_complex_fields/types_gen.go
testdata/jennies/rawtypes/struct_with_complex_fields/JavaRawTypes/struct_complex_fields/Constants.java
testdata/jennies/rawtypes/struct_with_complex_fields/JavaRawTypes/struct_complex_fields/SomeStruct.java
testdata/jennies/rawtypes/struct_with_complex_fields/PythonRawTypes/models/struct_complex_fields.py
testdata/jennies/rawtypes/struct_with_complex_fields/TypescriptRawTypes/src/struct_complex_fields/types_gen.ts
testdata/jennies/rawtypes/struct_with_complex_fields/ir.json

See the test case.
Cog currently generates invalid code for struct fields defined as a reference to a constant.

Fix generation of struct fields defined as a reference to a constant

---

.github/workflows/grafana-foundation-sdk-diff-preview.yaml

READMEs contain markdown that can break the output in PR comments and they don't provide meaningful information in that context. So we should be able to safely exclude them from the diff.

Exclude READMEs from the preview diff generated against grafana-foundation-sdk

---

internal/ast/builder.go

If a field is defined as a required reference to a constant, then we shouldn't define an option for it in builders.

Do not generate an option for fields defined as refs to a constant

---

internal/jennies/golang/templates/builders/assignment.tmpl
testdata/jennies/builders/builder_delegation/GoBuilder/builder_delegation/dashboard_builder_gen.go
testdata/jennies/builders/builder_delegation/PythonBuilder/builders/builder_delegation.py
testdata/jennies/builders/builder_delegation/TypescriptBuilder/src/builder_delegation/dashboard_builder_gen.ts
testdata/jennies/builders/builder_delegation/builders_context.json
testdata/jennies/builders/builder_delegation/schema.cue
testdata/jennies/builders/composable_slot/GoBuilder/composable_slot/lokibuilder_builder_gen.go
testdata/jennies/builders/struct_with_defaults/GoBuilder/struct_with_defaults/struct_builder_gen.go

```go
func (builder *InfluxQueryBuilder) Select(selectArg [][]cog.Builder[InfluxQueryPart]) *InfluxQueryBuilder {
selectArgResources := make([][]InfluxQueryPart, 0, len(selectArg))
for _, r1 := range selectArg {
selectArgDepth1 := make([]InfluxQueryPart, 0)
for _, r2 := range r1 {
selectArgDepth2, err := r2.Build()
if err != nil {
builder.errors["select"] = err.(cog.BuildErrors)
return builder
}
selectArgDepth1 = append(selectArgDepth1, selectArgDepth2)
}
selectArgResources = append(selectArgResources, selectArgDepth1)
}
builder.internal.Select = selectArgResources
return builder
}
```
Instead of 
```go
func (builder *InfluxQueryBuilder) Select(selectArg [][]cog.Builder[InfluxQueryPart]) *InfluxQueryBuilder {
selectArgResources := make([][]InfluxQueryPart, 0, len(selectArg))
for _, r := …
```

Support arbitrary nesting levels of arrays of builders in Go

---

internal/ast/compiler/rename_numeric_enum_values.go
internal/ast/compiler/rename_numeric_enum_values_test.go

Without this fix, the pass generates `N1` for both `-1` and `1`

Fix rename_numeric_enum_values compiler pass to handle negative values

---

cmd/cli/generate/command.go
internal/jennies/golang/builder.go
internal/jennies/golang/jennies.go
internal/jennies/java/jennies.go
internal/jennies/typescript/builder.go
internal/jennies/typescript/jennies.go
internal/veneers/builder/rules.go
internal/veneers/builder/selectors.go
internal/veneers/option/actions.go
internal/veneers/option/rules.go
internal/veneers/option/selectors.go
internal/veneers/rewrite/rewrite.go
internal/veneers/rewrite/rewrite_test.go
internal/yaml/veneers.go

Move veneer trail handling to a veneer (!) instead of duplicating its implementation in every jenny.
By having this done in a "debug" veneer, every jenny can benefit from this trail without knowing anything about it. That's one thing less in the list of many things to worry about when implementing a jenny.

Shared veneer trail handling

---

internal/ast/compiler/anonymous_enum_test.go
internal/ast/compiler/disjunctions_test.go
internal/ast/compiler/name_anonymous_struct_test.go
internal/ast/compiler/prefix_enum_values_test.go
internal/ast/compiler/rename_numeric_enum_values_test.go
internal/ast/compiler/rename_object.go
internal/ast/compiler/rename_object_test.go
internal/ast/compiler/unspec_test.go
internal/ast/types.go
internal/orderedmap/map.go
internal/orderedmap/map_test.go
internal/yaml/compilerpasses.go

https://github.com/vega/ts-json-schema-generator/ can sometimes generate object definitions with weird names (especially when the original type involves using generics).
As a result, having a way to rename some objects while maintaining the state of their references can be useful.
This PR adds a compiler pass to do just that.

Add "Rename Object" compiler pass

---

internal/ast/compiler/fields_set_default.go
internal/ast/compiler/fields_set_default_test.go
internal/yaml/compilerpasses.go

Figuring out default values when generating a JSON schema with https://github.com/vega/ts-json-schema-generator/ is currently an unsolved topic.
As a result, having a way to explicitly set some useful default values in cog can be useful.
This PR adds a compiler pass to do just that.

Add "Fields set default" compiler pass

---

internal/jennies/common/packagetemplate.go

To ensure that the output is deterministic and doesn't depend on the order with which schemas are parsed, let's sort the package list it gives to templates.

Sort packages list in PackageTemplate jenny

---

internal/jennies/golang/templates/runtime/variant_plugins.tmpl
internal/jennies/golang/variantsplugins.go

Similar to #282
To guarantee a consistent output, we sort packages in the `GoVariantsPlugins` jenny.

Sort packages list in GoVariantsPlugins jenny

---

internal/jennies/common/context.go
internal/jennies/golang/builder_test.go
internal/jennies/typescript/builder.go
internal/jennies/typescript/runtime.go
internal/jennies/typescript/templates/builder.tmpl
internal/jennies/typescript/tmpl.go
testdata/jennies/builders/builder_delegation_in_disjunction/PythonBuilder/builders/builder_delegation_in_disjunction.py
testdata/jennies/builders/builder_delegation_in_disjunction/TypescriptBuilder/src/builderDelegationInDisjunction/dashboardBuilder.gen.ts
testdata/jennies/builders/builder_delegation_in_disjunction/TypescriptBuilder/src/builderDelegationInDisjunction/dashboardLinkBuilder.gen.ts
testdata/jennies/builders/builder_delegation_in_disjunction/TypescriptBuilder/src/builderDelegationInDisjunction/externalLinkBuilder.gen.ts
testdata/jennies/builders/builder_delegation_in_disjunction/builders_context.json
testdata/jennies/builders/builder_delegation_in_disjunction/schema.cue

Cog generates invalid code in builders accepting a disjunction as arguments, if branches of that disjunction reference builders.
A few failing cases can be found in [testdata/jennies/builders/builder_delegation_in_disjunction/TypescriptBuilder/src/builderDelegationInDisjunction/dashboardBuilder.gen.ts](https://github.com/grafana/cog/pull/281/files#diff-2a945905c61362e677aba34c1db6348e7717bb652365285b70279f8374a3bfbe)
Note: this PR fixes a few cases, but there are still other cases where cog would generate incorrect code. For example:
```cue
broken: #DashboardLink | [...#DashboardLink]
otherBroken: [...#DashboardLink] | string
```
Would generate:
```patch
+    broken(broken: cog.Builder<builderDelegationInDisjunction.DashboardLink> | …
```

Improve support for disjunctions as option arguments in builders

---

internal/jennies/typescript/rawtypes.go

`ts-node` in the CI pipeline picked that up in my previous PR. Not sure why this didn't pop up before :shrug:

Escape enum members names "nan" in TS as it is an invalid identifier

---

.github/workflows/ci.yaml
schemas/composable/prometheus/dataquery.cue
scripts/consolidate-schema-registry.sh
scripts/release-version.sh

CUE [schemas for prometheus dataqueries have been removed from Grafana](https://github.com/grafana/grafana/pull/83808).
As a result, they're not present in kind-registry in the `next` version (but the list of impacted versions will grow).
Until we figure out better ways to get schemas, I propose that we cheat a bit and "consolidate" what we get from the kind-registry to retain the ability to generate grafana-foundation-sdk.

Consolidate kind-registry to temporarily accomodate for deleted schemas

---

config/compiler/common_passes.yaml
examples/_go/disk.go
internal/ast/compiler/fields_set_not_required.go
internal/yaml/compilerpasses.go

Fixes grafana/grafana-foundation-sdk#50

Set a compiler pass to mark common.TableFieldOptions.CellOptions as not required

---

config/compiler/common_passes.yaml
internal/ast/types.go

See https://github.com/grafana/cog/issues/292
The fix doesn't appear to be trivial, so in the meantime I use compiler passes to "fix" the IR.

Dirty fix for incorrectly parsed candlestick and heatmap objects

---

examples/python/main.py
internal/jennies/python/rawtypes.go
internal/jennies/python/runtime.go
internal/jennies/python/templates/runtime/plugins.tmpl
internal/jennies/python/templates/runtime/runtime.tmpl
internal/jennies/python/templates/runtime/variant_models.tmpl
internal/jennies/python/types.go
testdata/jennies/rawtypes/arrays/PythonRawTypes/models/arrays.py
testdata/jennies/rawtypes/disjunctions/PythonRawTypes/models/disjunctions.py
testdata/jennies/rawtypes/field_with_struct_with_defaults/PythonRawTypes/models/defaults.py
testdata/jennies/rawtypes/maps/PythonRawTypes/models/maps.py
testdata/jennies/rawtypes/package-with-dashes/PythonRawTypes/models/with-dashes.py
testdata/jennies/rawtypes/refs/PythonRawTypes/models/refs.py
testdata/jennies/rawtypes/struct_with_complex_fields/PythonRawTypes/models/struct_complex_fields.py
testdata/jennies/rawtypes/struct_with_defaults/PythonRawTypes/models/defaults.py
testdata/jennies/rawtypes/struct_with_optional_fields/PythonRawTypes/models/struct_optional_fields.py
testdata/jennies/rawtypes/struct_with_scalar_fields/PythonRawTypes/models/basic.py

This PR adds support for unmarshalling json into types in Python.
The approach followed to make sure "composable slots" are unmarshalled properly (panels + dataqueries) is similar to what we did for Go.

Support decoding from JSON in Python

---

config/compiler/common_passes.yaml

Similar to https://github.com/grafana/cog/pull/293
Relates to https://github.com/grafana/cog/issues/292

Manually fix incorrectly parsed type for `heatmap.Options.tooltip`

---

internal/jennies/python/jennies.go

Needed for schemas that don't provide names for enum members.

Use "RenameNumericEnumValues" compiler pass for python

---

internal/ast/builder.go
internal/ast/compiler/anonymous_enum.go
internal/ast/compiler/anonymous_structs_to_named.go
internal/ast/compiler/cloudwatch.go
internal/ast/compiler/dataquery_identification.go
internal/ast/compiler/disjunctions.go
internal/ast/compiler/disjunctions_infer_mapping.go
internal/ast/compiler/disjunctions_with_null_to_optional.go
internal/ast/compiler/flatten_disjunctions.go
internal/ast/compiler/googlecloudmonitoring.go
internal/ast/compiler/librarypanels.go
internal/ast/compiler/name_anonymous_struct.go
internal/ast/compiler/not_required_as_nullable.go
internal/ast/compiler/rename_object.go
internal/ast/schema.go
internal/ast/tools.go
internal/ast/types.go
internal/jennies/common/context.go
internal/jennies/golang/builder.go
internal/jennies/golang/jsonmarshalling.go
internal/jennies/golang/tmpl.go
internal/jennies/golang/types.go
internal/jennies/java/rawtypes.go
internal/jennies/python/rawtypes.go
internal/jennies/python/types.go
internal/jennies/typescript/builder.go
internal/jennies/typescript/rawtypes.go
internal/jennies/typescript/types.go
internal/veneers/option/actions.go

Just a refactoring/cleanup: instead of directly comparing a type's kind with a constant, let's use the `IsX()` utility methods instead.
This PR doesn't change the generated code.

Replace a few kind checks by their utility 'IsX' function

---

internal/ast/compiler/anonymous_structs_to_named.go
internal/jennies/golang/builder.go
internal/jennies/golang/templates/builders/assignment.tmpl

I noticed that our go jenny generates incorrect code for the empty value of a struct that has a builder:
```go
builder.internal.Time = cog.Builder[DashboardDashboardTime]{}
```
Instead of:
```go
builder.internal.Time = &DashboardDashboardTime{}
```
This bug doesn't appear in the foundation-sdk since it required enabling the `AnonymousStructsToNamed` compiler pass (which isn't enabled for Go at the moment), but it was easy to fix so here we are.

Fix empty value generation for go types with builders

---

.github/workflows/grafana-foundation-sdk-diff-preview.yaml

It skips foundation-sdk preview for `dependabot` PR's since they fail because a lack of authorization.

Skip foundation-sdk preview when is dependabot

---

repository_templates/python/.github/workflows/python-release.yaml

`grafana-foundation-sdk` has been setup using [PyPI's trusted publishing](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/), so we can now uncomment this :)

Enable Python package publishing in grafana-foundation-sdk release pipeline

---

.github/workflows/grafana-foundation-sdk-diff-preview.yaml

PRs like this: https://github.com/grafana/cog/pull/310 fail because of missing permissions. We want the workflow to run but just not post the comments

Attempt at fixing dependabot PRs

---

.github/workflows/grafana-foundation-sdk-diff-preview.yaml

For https://github.com/grafana/cog/pull/315, I removed the comment for dependabot PRs so we don't see the diff anymore
With this change, we'll see it in CI logs at least

CI: Print out the diff when generating the foundation SDK

---

package_templates/go/README.md
package_templates/python/README.md
package_templates/typescript/README.md

This PR is a first pass at improving the READMEs in `grafana-foundation-sdk`.
The first commit is mostly cosmetic, while the last two add more information on the Go readme on how to deal with custom query/panel types.
I'll add the same type of examples in the Typescript and Python READMEs in other PRs.

Improve readmes

---

scripts/release-version.sh

Will allow us to replace grok as input for grafonnet.

Release jsonschema and OpenAPI specs to foundation-sdk

---

go.mod
go.sum
internal/openapi/generator.go
internal/openapi/utils.go

Supersedes https://github.com/grafana/cog/pull/309 
The type is now an array, so we should handle that

Upgrade `kin-openapi` library

---

internal/jennies/golang/jsonmarshalling.go
testdata/jennies/rawtypes/dashboard/GoJSONMarshalling/dashboard/types_json_marshalling_gen.go

Possible fix for https://github.com/grafana/cog/issues/328, this change adds a presence check for the field before delegating to the `UnmarshalDataquery(Array)` function. An example of this applied to the kind-registry can be found [here](https://github.com/andybradshaw/grafana-foundation-sdk/blob/a49c19b26112212583151d32828235f633ed148e/go/dashboard/types_json_marshalling_gen.go#L195-L201):
```golang
if fields["targets"] != nil {
targets, err := cog.UnmarshalDataqueryArray(fields["targets"], dataqueryTypeHint)
if err != nil {
return err
}
resource.Targets = targets
}
```

Update json marshalling of dataquery types

---

internal/ast/compiler/prefix_enum_values.go
internal/ast/compiler/prefix_enum_values_test.go

Allows us to generate correct enum member names for cases like:
```json
"enum": [
"",
"timeseries-wide",
"timeseries-long",
"timeseries-many",
"timeseries-multi",
"directory-listing",
"table",
"numeric-wide",
"numeric-multi",
"numeric-long",
"log-lines"
],
```

Fix PrefixEnumValues compiler pass to handle empty string members

---

internal/jsonschema/generator.go
internal/openapi/generator.go
internal/tools/regexp.go
testdata/jsonschema/consts/GenerateAST/ir.json
testdata/jsonschema/consts/schema.json
testdata/openapi/consts/GenerateAST/ir.json
testdata/openapi/consts/schema.json

Some schemas choose to express constant values using a regex (see test cases). This PR introduces a bit of a hack to correctly identify these cases and parse them as actual constant scalar values in our IR.

Parse "constant" regexes as actual constants in Jsonschema and OpenAPI

---

internal/ast/compiler/filter_schemas.go
internal/ast/compiler/filter_schemas_test.go

In order to generate alerting-related code for the foundation-sdk, we would need to use [Grafana's OpenAPI spec](https://github.com/grafana/grafana/blob/main/public/openapi3.json) in addition to schemas from the [kind-registry](https://github.com/grafana/kind-registry/).
Not everything in that spec is relevant for alerting purposes though, so we'll need a way to easily target "entrypoint objects" for which we want to generate code.
This PR defines a compiler pass that will enable just that: given some objects, identify all their dependencies and filter out everything else.
Note: it's not used anywhere yet, that will come later :)

Add a FilterSchemas compiler pass

---

internal/jsonschema/generator.go
testdata/jsonschema/allof_object/GenerateAST/ir.json
testdata/jsonschema/allof_object/schema.json
testdata/jsonschema/oneof_object/GenerateAST/ir.json
testdata/jsonschema/oneof_object/schema.json

The jsonschema parser wasn't able to correctly parse oneOf/anyOf/allOf definitions that had a `"type": "object"` attribute (it would incorrectly parse them as an object with no properties).

Fix parsing of oneOf/allOf/anyOf typed as objects in jsonschema

---

internal/ast/compiler/disjunctions_of_anonymous_to_explicit.go
internal/ast/compiler/disjunctions_of_anonymous_to_explicit_test.go
internal/ast/compiler/flatten_disjunctions.go
internal/ast/compiler/flatten_disjunctions_test.go
internal/jennies/golang/jennies.go

The "disjunction flattening" compiler pass gets confused when anonymous structs are part of the disjunction. This results in parts of the schema mysteriously being flattened away :sweat_smile: 
This PR fixes this issue.

Fix disjunction flattening for anonymous branches

---

internal/ast/compiler/retype_object.go
internal/ast/compiler/retype_object_test.go
internal/yaml/compilerpasses.go

Sometimes, schemas lie to us and we need a way to fix that.

Add a "RetypeObject" compiler pass

---

go.mod
go.sum
internal/jennies/jsonschema/jennies.go
internal/jsonschema/generator.go
internal/jsonschema/utils.go

We currently depend on santhosh-tekuri/jsonschema v1.2.4, while v5.3.1 is out :scream:

Bump santhosh-tekuri/jsonschema to v5

---

examples/typescript/index.ts
internal/jennies/typescript/builder.go
internal/jennies/typescript/templates/args.tmpl
internal/jennies/typescript/templates/builder.tmpl
internal/jennies/typescript/tmpl.go
internal/jennies/typescript/tools.go

Some schemas describe objects with property names that are reserved keywords in typescript. Let's escape them.

Escape identifiers in typescript

---

cmd/cli/loaders/openapi.go
internal/openapi/generator.go

Can be useful to ignore validation issues that wouldn't impact codegen.
Example:
```
Error: [alerting] invalid paths: operation GET /reports/render/pdf/{dashboardID} must define exactly all path parameters (missing: [DashboardID])
```

Support disabling OpenAPI spec validation

---

internal/jennies/python/types.go
testdata/jennies/rawtypes/arrays/PythonRawTypes/models/arrays.py
testdata/jennies/rawtypes/disjunctions/PythonRawTypes/models/disjunctions.py
testdata/jennies/rawtypes/maps/PythonRawTypes/models/maps.py
testdata/jennies/rawtypes/package-with-dashes/PythonRawTypes/models/with-dashes.py
testdata/jennies/rawtypes/refs/PythonRawTypes/models/refs.py
testdata/jennies/rawtypes/scalars/PythonRawTypes/models/scalars.py

Make type alias explicitly declared in Python.
This fixes some linting errors returned by mypy when generating alerting-related code

Proper generation of type aliases in python

---

internal/ast/builder.go
internal/jennies/golang/builder.go
internal/jennies/golang/templates/builders/constraints.tmpl
internal/jennies/golang/tmpl.go
internal/jennies/golang/tools.go
internal/jennies/golang/types.go
internal/jennies/java/builders.go
internal/jennies/java/templates/types/constraints.tmpl
internal/jennies/python/builder.go
internal/jennies/python/templates/builders/constraints.tmpl
internal/jennies/template/models.go
internal/jennies/typescript/builder.go
internal/jennies/typescript/templates/constraints.tmpl
internal/tools/arrays.go
internal/veneers/option/actions.go
testdata/jennies/builders/constraints/builders_context.json
testdata/jennies/builders/constraints/schema.cue

Similar to #357
With a few tweaks on how assignment constraints are represented in the builder IR, we can reduce the amount of work/manipulations that jennies have to do.

Better representation of constraints in the builder IR

---

internal/jennies/java/rawtypes.go
internal/jennies/java/tools.go
testdata/jennies/rawtypes/package-with-dashes/JavaRawTypes/withdashes/RefreshRate.java
testdata/jennies/rawtypes/package-with-dashes/JavaRawTypes/withdashes/SomeStruct.java
testdata/jennies/rawtypes/package-with-dashes/JavaRawTypes/withdashes/StringOrBool.java

Contributes to: https://github.com/grafana/cog/issues/235
Java packages don't allow to have dashes in their packages/folders names.

Java: Remove dashes from Java packages and folders

---

internal/jennies/java/rawtypes.go
internal/jennies/java/tools.go

Contributes to: https://github.com/grafana/cog/issues/360
* It sets default "None" value when enum name doesn't exist. It generates the model like in Go.
* It escapes reserved words from paths to make it works.

Java: Fix empty enum values and escape reserved words

---

config/veneers/dashboard.common.yaml

While adding one annotation/variable/link/... at a time is convenient, there is no reason why there should be no option to set all the values at once.

Define more veneers on dashboards/panels

---

cmd/cli/loaders/config.go
go.mod
go.sum
internal/semver/semver.go

Will be useful for #374, for which we need to load a schema from Grafana only for versions >= v11.0.x
The config looks like:
```yaml
inputs:
- if: '"%grafana_version%" == "main" || semver("%grafana_version%").MoreThanEqual(semver("v11.0.x"))'
jsonschema:
url: 'https://raw.githubusercontent.com/grafana/grafana/%grafana_version%/pkg/tsdb/grafana-testdata-datasource/kinds/query.panel.schema.json'
package: testdata
```

Support conditional schema loading

---

internal/ast/compiler/add_fields.go
internal/ast/compiler/add_fields_test.go
internal/ast/compiler/disjunction_with_constant_to_default.go
internal/ast/compiler/disjunctions.go
internal/ast/compiler/disjunctions_infer_mapping.go
internal/ast/compiler/disjunctions_of_anonymous_to_explicit.go
internal/ast/compiler/disjunctions_with_null_to_optional.go
internal/ast/compiler/fields_set_default.go
internal/ast/compiler/fields_set_not_required.go
internal/ast/compiler/fields_set_required.go
internal/ast/compiler/filter_schemas.go
internal/ast/compiler/flatten_disjunctions.go
internal/ast/compiler/hint_object.go
internal/ast/compiler/not_required_as_nullable.go
internal/ast/compiler/retype_field.go
internal/ast/compiler/retype_object.go
internal/ast/compiler/types.go
internal/ast/compiler/visitor.go
internal/ast/schema.go

This PR introduces a "types IR" visitor that provides a reusable way to explore and modify the types IR.
Extracting this logic allows us to simplify a fair few of our existing compiler passes.

Improve tools to visit and modify the types IR

---

config/compiler/kind_registry.yaml

Without these defaults, some panels display no data and/or crash when editing them from the UI.

Define some missing default values for timeseries and legends

---

cmd/cli/loaders/config.go
internal/jennies/jsonschema/jennies.go
internal/jennies/jsonschema/schema.go
internal/jennies/jsonschema/schema_test.go
internal/jennies/openapi/jennies.go
internal/jennies/openapi/schema.go
internal/jennies/openapi/schema_test.go

Whether JSONSchema and OpenAPI schemas are generated in a compact for or not should not be controlled by the debug flag only.

Configurable compact output for JSONSchema and OpenAPI

---

config/compiler/kind_registry.yaml

This field is missing upstream for Grafana<=v11.0.0
Added here: https://github.com/grafana/grafana/pull/85861

fix(compilerpass/kind_registry): add common.GraphFieldconfig.insertNulls

---

internal/jennies/java/builders.go

0 value is interpreted as integer and we need to map it into a float when the ScalarKind is set as float.

Java: Fix float defaults

---

Makefile
cmd/compiler-passes-docs/main.go
docs/compiler_passes.md
internal/yaml/compilerpasses.go

Rather than having to look at the source to know which compiler passes are usable, we could generate a markdown file to list them.
Warning: the generation process for this doc relies on dark magic :see_no_evil:

Add a quick and dirty script to generate a list of configurable compiler passes

---

internal/jennies/java/rawtypes.go
internal/jennies/java/types.go
testdata/jennies/builders/nullable_map_assignment/JavaBuilders/nullable_map_assignment/SomeStruct.java
testdata/jennies/rawtypes/struct_with_complex_fields/JavaRawTypes/struct_complex_fields/SomeStruct.java

Maps were adding the import only for references and we weren't checking if a reference was an array. In this second case, we were setting values like `Matchers` and `ObjectMatchers` that are array aliases and they aren't allowed in Java.
Before:
```java
public Matchers matchers;
public ObjectMatchers objectMatchers;
```
After:
```java
public List<Matcher> matchers;
public List<List<String>> objectMatchers;
```

Java: Fix alerting generation

---

config/veneers/dashboard.common.yaml
internal/jennies/golang/templates/builders/veneers/assignment_Dashboard_withPanel.tmpl
internal/jennies/golang/templates/builders/veneers/assignment_Dashboard_withRow.tmpl
internal/jennies/java/templates/veneers/assigment_Dashboard_WithPanel.tmpl
internal/jennies/python/templates/builders/veneers/assignment_Dashboard_withPanel.tmpl
internal/jennies/python/templates/builders/veneers/assignment_Dashboard_withRow.tmpl
internal/jennies/typescript/templates/veneers/assignment_Dashboard_withPanel.tmpl
internal/jennies/typescript/templates/veneers/assignment_Dashboard_withRow.tmpl

While the span/height-based automatic layout for panels is convenient, having a way to manually position panels in a dashboard can be useful (especially when users want a specific and _non-standard_ layout)

Expose a way to manually position panels in a dashboard

---

internal/simplecue/generator.go

Including all CUE expressions when exploring CUE values to envelope is too wide: it means traversing hidden values too, which we don't want.
Additionally, we need to check whether the values we find are optional or not.

Fix fields parsing from enveloped types in CUE

---

cmd/cli/codegen/output.go
cmd/cli/codegen/pipeline.go
internal/jennies/golang/jennies.go
internal/jennies/java/jennies.go
internal/jennies/python/jennies.go
internal/jennies/typescript/builder_test.go
internal/jennies/typescript/jennies.go
internal/jennies/typescript/rawtypes_test.go

Mirrors #409 for every other language supported by cog.

Add an option to skip runtime generation for all languages

---

internal/ast/compiler/append_comment_objects.go
internal/ast/compiler/append_comment_objects_test.go

`grafana-app-sdk` needs to add a specific comment to every generated object: https://github.com/grafana/grafana-app-sdk/blob/e46439fe213e5e34126d25d66dcd2670db2c95c1/codegen/jennies/dstutil.go#L13-L27
Relates to #408

Add an "AppendCommentObjects" compiler pass

---

cmd/cli/codegen/cue.go
cmd/cli/codegen/kindsyscomposable.go
cmd/cli/codegen/kindsyscore.go
internal/simplecue/generator.go

Relates to #408 
To integrate with `grafana-app-sdk`, cog will need to parse CUE values instead of files. These values might not define a "root" object for the schema, in which case a "named envelope" needs to be used to introduce one.

Better support for cue schemas with a forced named envelope

---

internal/ast/compiler/disjunctions_infer_mapping.go
internal/ast/compiler/disjunctions_infer_mapping_test.go
internal/ast/compiler/undiscriminated_disjunctions_to_any.go
internal/ast/compiler/undiscriminated_disjunctions_to_any_test.go
internal/ast/types.go
internal/jennies/golang/jennies.go

Rather than failing if we can't handle a disjunction correctly, let's "degrade gracefully" and turn the disjunction to an `any` type.

Add a compiler pass to turn undiscriminated disjunctions to any

---

internal/jennies/typescript/jennies.go

Relates to #408 
In some cases, we're really only interested in generating types. So let's support that in typescript too.

Add an option to skip index.ts files generation in Typescript

---

config/veneers/prometheus.yaml
examples/_go/common.go
examples/_go_alerting/main.go
examples/python/raspberry/common.py
examples/typescript/common.ts
internal/veneers/builder/rules.go
internal/veneers/option/actions.go
internal/veneers/option/rules.go
internal/veneers/types.go
internal/yaml/builder.go
internal/yaml/option.go

This PR makes it more intuitive to define range/instant queries in prometheus. The API now exposed for this follows what the UI does.

Make working with instant/range prometheus queries more intuitive

---

internal/jennies/golang/builder_test.go
internal/jennies/golang/rawtypes_test.go
internal/jennies/java/builders_test.go
internal/jennies/java/rawtypes_test.go
internal/jennies/jsonschema/schema_test.go
internal/jennies/openapi/schema_test.go
internal/jennies/python/builder_test.go
internal/jennies/python/rawtypes_test.go
internal/jennies/typescript/builder_test.go
internal/jennies/typescript/rawtypes_test.go
internal/jsonschema/generator_test.go
internal/openapi/generator_test.go
internal/simplecue/generator_test.go
internal/testutils/constants.go
internal/testutils/jennytestsuite.go

A bit of cleaning, to remove duplicated code and unnecessary couplings in txtar test utils.

Cleanup txtar utils to decouple them from inputs being tested

---

internal/ast/compiler/prefix_object_names_test.go
internal/ast/compiler/prefix_objects_names.go
internal/ast/compiler/rename_object.go
internal/ast/compiler/visitor.go

Adds a compiler pass that alters object names to add a prefix to them.
This is to support an existing feature in grafana-app-sdk's codegen: https://github.com/grafana/grafana-app-sdk/blob/9643ce43ef07d9218303db5722be6e04ab9d1f3b/codegen/jennies/gotypes.go#L174-L175
Contributes to #408

Compiler pass/prefix object names

---

internal/jennies/java/templates/types/panel_builder.tmpl
testdata/jennies/builders/panel_builders/GoBuilder/panelbuilder/panel_builder_gen.go
testdata/jennies/builders/panel_builders/JavaBuilders/panelbuilder/Options.java
testdata/jennies/builders/panel_builders/JavaBuilders/panelbuilder/PanelBuilder.java
testdata/jennies/builders/panel_builders/PythonBuilder/builders/panelbuilder.py
testdata/jennies/builders/panel_builders/TypescriptBuilder/src/panelbuilder/panelBuilder.gen.ts
testdata/jennies/builders/panel_builders/builders_context.json

It adds tests for Panels to see how its generated in Java since its a bit different comparing with the other languages. The example it isn't the same panel as we could have in Grafana but we can verify that its generated.
I saw that I forgot to add the defaults in panel builders for Java 🙈.

Builders: Tests for panel builders

---

internal/jennies/java/builders.go
testdata/jennies/builders/composable_slot/JavaBuilders/composable_slot/Dashboard.java
testdata/jennies/builders/dataquery_variant_builder/JavaBuilders/dataquery_variant_builder/Loki.java
testdata/jennies/builders/panel_builders/GoBuilder/panelbuilder/panel_builder_gen.go
testdata/jennies/builders/panel_builders/PythonBuilder/builders/panelbuilder.py
testdata/jennies/builders/panel_builders/TypescriptBuilder/src/panelbuilder/panelBuilder.gen.ts
testdata/jennies/builders/panel_builders/builders_context.json

In Java we have a map of builders used to decide if we should add the builder or not inside the class (common way to do in Java).
The problem is we were iterating the builder structure only and the names of the Builders differs from the one in Schema and it was impossible to find them.

Java: Use schema object name to create the map of builders

---

internal/codegen/cue.go
internal/simplecue/generator.go
internal/simplecue/generator_test.go

Contributes to #408
This PR allows the object naming strategy used in our CUE parser to be configured. This ability is needed for `grafana-app-sdk`: https://github.com/grafana/grafana-app-sdk/blob/9481a3eaa83c509c6a35cc0f71bd201955cbfa8e/codegen/jennies/gotypes.go#L182-L196

Support custom object naming strategies in cue parser

---

internal/jennies/java/builders.go
internal/jennies/java/builders_test.go
internal/jennies/java/jennies.go

It allows to skip builder's generation following the same rules than other languages.

Java: Allow to skip builders generation

---

internal/ast/compiler/inline_scalar_aliases.go
internal/ast/compiler/inline_scalar_aliases_test.go
internal/ast/compiler/utils_test.go
schemas/pipeline.json

This compiler pass will make it easier to support languages that do not allow type aliases for scalar.
Example in TS:
```typescript
type UserID = string
```

Add InlineScalarAliases compiler pass

---

internal/jennies/java/templates/types/builder.tmpl

Constructor name and function returns should use the class name.

Java: Fix multiple constructors names

---

internal/jennies/java/builders.go
internal/jennies/java/templates/types/builder.tmpl
internal/jennies/java/templates/types/class.tmpl

The current behaviour to set the builder name in the builders where they have multiple ones, breaks the template venners. We are removing the builderName to avoid to set it when we only have one builder, but it makes impossible to find the veneer template because of that. You can see [here](https://github.com/grafana/cog/blob/main/internal/jennies/java/templates/types/assigments.tmpl#L11-L12) and [here](https://github.com/grafana/cog/blob/main/internal/jennies/java/templates/types/assigments.tmpl#L16-L17).
So the PR is adding the first approach that we did pairing.

Java: Fix veneers templates

---

internal/jennies/java/builders.go
internal/jennies/java/pom.go
internal/jennies/java/templates/types/builder.tmpl
internal/jennies/java/templates/types/panel_builder.tmpl
internal/jennies/java/tmpl.go
internal/jennies/java/tools.go
internal/veneers/option/actions.go
testdata/jennies/builders/basic_struct_defaults/JavaBuilders/basic_struct_defaults/SomeStruct.java
testdata/jennies/builders/struct_with_defaults/JavaBuilders/struct_with_defaults/Struct.java

Unlike the other languages, we cannot initialise a builder/object with values directly in the setter of the function.
For that, it adds an initialiser array to create the object or builder for that default and set the result into the setter.
There is a lot of issues with the defaults between floats and integers. Sometimes an integer could be a float or vice versa, and its why there are some comments related to this.
Finally I found an issue where we can have setters with the same argument and defaults could have a conflict generating the same object/builder names. You can see in [one](https://github.com/grafana/cog/compare/java/fix-defaults?expand=1#diff-d24b024fa03915ad74ad425eb05b6c6d00d03bf1306b2ee7b0da71092a2ecf75R16) of the tests. There is a `TODO` comment for this.

Java: Fix reference defaults

---

cmd/cog-config-schemas/main.go
schemas/compiler_passes.json
schemas/pipeline.json
schemas/veneers.json

Some definitions conflicted with each others in our config schemas due to identical names.
To lift this kind of ambiguity, I tweaked the schema-generator to use both the package name and the object name when generating a definition.

Disambiguate name conflicts in config schemas

---

config/compiler/testdata_passes.yaml

All renaming names are in upper camel case except this one. It generates wrong Java code.

Compiler: Fix testdata datasource name

---

examples/_as_library/main.go
go.mod
go.sum
helpers.go
internal/ast/compiler/prefix_objects_names.go
internal/codegen/input.go
internal/codegen/pipeline.go
internal/codegen/run.go
internal/codegen/transforms.go
internal/openapi/generator.go
internal/openapi/utils.go

Contributes to #408 
[`grafana-app-sdk`](https://github.com/grafana/grafana-app-sdk) wants to rely on cog for some of its codegen-related use-cases, especially to generate Go and Typescript types from a single CUE value.
This PR is a proposition of a minimal API that would allow `grafana-app-sdk` to use cog as a library to achieve these goals.
A sandbox PR is open to see how it would look like on the other side of the fence: https://github.com/grafana/grafana-app-sdk/pull/296

Cog as library

---

internal/jennies/java/builders.go
internal/jennies/java/templates/types/builder.tmpl

It adds the package prefix to Dataquery builders implementations when it's the same name than the class name, to point to the variant's Dataquery.

Java: Fix dataquery implementations

---

internal/jennies/java/templates/types/builder.tmpl
internal/jennies/java/templates/veneers/assigment_Dashboard_WithPanel.tmpl
internal/jennies/java/types.go
testdata/jennies/builders/properties/JavaBuilders/properties/SomeStruct.java

There are some NPE with properties because aren't initialised and veneer template needs some null-checks.

Java: Initialise properties and null-checks

---

scripts/release-version.sh

Otherwise there's a risk of us releasing a foundation-sdk based on outdated schemas :|

Ensure the local kind-registry is up-to-date before releasing

---

internal/ast/compiler/remove_intersections.go
internal/jennies/java/types.go

This PR fixes some issues when we a class extends from a List and, in that case, we want to use the list directly. This is was working as an alias that didn't work because extending from a list/map needs extra implementations.
Apart of this, it fixes the case when a map value is ref of an `any` scalar.

Java: Fix aliases

---

package_templates/go/README.md
package_templates/python/README.md
package_templates/typescript/README.md

Let's update the maturity statement displayed in the foundation-sdk to something less scary, reflecting the actual state of the sdk.

Update the foundation-sdk maturity statement to "public preview"

---

examples/php/index.php
internal/jennies/php/rawtypes.go
testdata/jennies/rawtypes/struct_with_complex_fields/PHPRawTypes/src/StructComplexFields/ConnectionPath.php
testdata/jennies/rawtypes/struct_with_complex_fields/PHPRawTypes/src/StructComplexFields/Constants.php

In PHP, constants can't be autoloaded if they're not defined within a class.
Contributes to #470

Fix constants generation in PHP

---

repository_templates/php/.github/workflows/php-ci.yaml

The composer.json file moved in https://github.com/grafana/cog/pull/492
Contributes to #470

Fix PHP CI in foundation-sdk

---

internal/jennies/java/jsonmarshalling.go
internal/jennies/java/rawtypes.go
internal/jennies/java/templates/marshalling/disjunctions.json_marshall.tmpl
internal/jennies/java/templates/marshalling/marshalling.tmpl
internal/jennies/java/templates/types/class.tmpl
internal/jennies/java/tmpl.go
internal/jennies/java/tools.go

It fixes the marshalling for disjunctions (refs and scalars). For example, when you add a panel or a row inside panel's array in the dashboard, you are expecting to have the internal structure of a panel or row. In Java we were adding the whole disjunction struct adding extra values.
The expected behaviour is:
```json
{
"panels": [{ "type": "row" }, { "type": "panel" }]
}
```
And in Java we had:
```json
"panels": [{"row": { "type": "row" }}, {"panel": { "type": "panel" }}]
```
And a Java example to see better what's the code is doing:
```java
public class StringOrMap {
@JsonProperty("string")
public String string;
@JsonProperty("map")
public Map<String, Object> map;
public String toJSON() throws JsonProcessingException {
ObjectWriter ow = new …
```

Java: Marshalling

---

internal/simplecue/generator.go
testdata/simplecue/refs/GenerateAST/ir.json
testdata/simplecue/refs/schema.cue

In cue, the following _inline_ definition is currently parsed as a field instead of an object:
```cue
container: {
#SomeInlineDefinition: {
field: string
}
inline: #SomeInlineDefinition
}
```

Correctly parse inline definitions in cue

---

internal/jennies/java/templates/types/enum.tmpl
testdata/jennies/builders/constructor_initializations/JavaBuilders/constructor_initializations/CursorMode.java
testdata/jennies/rawtypes/enums/JavaRawTypes/enums/DashboardCursorSync.java
testdata/jennies/rawtypes/enums/JavaRawTypes/enums/LogsSortOrder.java
testdata/jennies/rawtypes/enums/JavaRawTypes/enums/Operator.java
testdata/jennies/rawtypes/enums/JavaRawTypes/enums/TableSortOrder.java
testdata/jennies/rawtypes/struct_with_complex_fields/JavaRawTypes/struct_complex_fields/SomeStructOperator.java
testdata/jennies/rawtypes/struct_with_optional_fields/JavaRawTypes/struct_optional_fields/SomeStructOperator.java

It adds extra annotations in enums to be able to map a string/integer into a enum value. Additionally it adds the final modifier to avoid to indicate that the value is immutable.

Java: Fix enum unmarshalling

---

internal/jennies/java/registry.go
internal/jennies/java/templates/runtime/empty_dataquery.tmpl
internal/jennies/java/templates/runtime/empty_dataquery_serializer.tmpl

The empty dataquery (used when we receive an unknown dataquery) were mapped into an `elasticsearch` type 🤡 since a copy&paste issue.
This empty dataquery includes a generic map to save the information, but it was adding `genericFields` field into the json result.
With this change, it removes this field adding only the included values.

Java: Add empty dataquery serializer

---

.github/workflows/ci.yaml
repository_templates/java/.github/workflows/java-ci.yaml
repository_templates/java/.github/workflows/java-release.yaml

Missing `actions/checkout@v4` step and `gradle build` should be a different step.

Java: Fix release templates

---

internal/jennies/golang/runtime.go
internal/jennies/golang/templates/runtime/runtime.tmpl
internal/jennies/golang/templates/runtime/variant_models.tmpl
internal/jennies/golang/templates/types/variant_dataquery.json_unmarshal.tmpl
internal/jennies/golang/templates/types/variant_panelcfg.json_unmarshal.tmpl
internal/jennies/golang/tools.go
package_templates/go/README.md
testdata/jennies/builders/composable_slot/GoBuilder/composable_slot/lokibuilder_builder_gen.go
testdata/jennies/builders/dataquery_variant_builder/GoBuilder/dataquery_variant_builder/lokibuilder_builder_gen.go
testdata/jennies/rawtypes/dashboard/GoRawTypes/dashboard/types_gen.go
testdata/jennies/rawtypes/variant_dataquery/GoRawTypes/variant_dataquery/types_gen.go
testdata/jennies/rawtypes/variant_panelcfg_full/GoRawTypes/variant_panelcfg_full/types_gen.go
testdata/jennies/rawtypes/variant_panelcfg_only_options/GoRawTypes/variant_panelcfg_only_options/types_gen.go

Fixes https://github.com/grafana/grafana-foundation-sdk/issues/190
We were using `cogvariants` instead of variants because the sanitiser removes all invalid characters of the aliases. When we add a variant we need to pass the cog/variants package and it's why this result.
The change is assuming that all packages fit with the directory name. The only exception that we had was cogvariants, so it should work for all of the cases.

Go: Use variants package for cogvariants.

---

internal/jennies/terraform/models.go
testdata/jennies/rawtypes/package-with-dashes/TerraformModels/withdashes/models_gen.go

It removes dashes from Terraform package names.

Terraform: Remove dashes from package name

---

internal/simplecue/generator.go

Doing some tests, this specific function generates errors with some projects. Selector does the same and its compatible with different Cue versions.

Cue: Use Selector instead of FieldType

---

.github/workflows/ci.yaml
.golangci.yaml

Golang 1.23 is available in version 1.60.3 onwards. We need this change to make https://github.com/grafana/cog/pull/520 works.

CI: Update golangci-lint

---

scripts/release-all.sh

Adds v11.2.x version to generate its builders.
For any reason (probably a bug), v11.1.x doesn't exist in kind-registry 🤷🏼‍♀️

Version: Adds v11.2.x kind-registry version

---

config/veneers/dashboard.common.yaml
internal/veneers/builder/rules.go
internal/yaml/builder.go

Closes https://github.com/grafana/cog/issues/527
It creates an action to avoid to lose defaults when we modify the options of the builders. These defaults will appear in the constructors of each language that uses Builders to parse the defaults.
We have important defaults like `schemaVersion` where we are omitting its option and loosing its value.
_Note_: Probably it could have coolest way to do it but its the cleanest way that I found to solve the issue.

Rules: Add DefaultToConstant rule

---

internal/jennies/java/types.go
testdata/jennies/builders/anonymous_struct/JavaBuilders/anonymous_struct/SomeStruct.java
testdata/jennies/builders/array_append/JavaBuilders/sandbox/SomeStruct.java
testdata/jennies/builders/basic_struct/JavaBuilders/basic_struct/SomeStruct.java
testdata/jennies/builders/basic_struct_defaults/JavaBuilders/basic_struct_defaults/SomeStruct.java
testdata/jennies/builders/builder_delegation/JavaBuilders/builder_delegation/Dashboard.java
testdata/jennies/builders/builder_delegation_in_disjunction/JavaBuilders/builder_delegation_in_disjunction/Dashboard.java
testdata/jennies/builders/composable_slot/JavaBuilders/composable_slot/Dashboard.java
testdata/jennies/builders/constant_assignment/JavaBuilders/sandbox/SomeStruct.java
testdata/jennies/builders/constructor_initializations/JavaBuilders/constructor_initializations/SomePanel.java
testdata/jennies/builders/envelope_assignment/JavaBuilders/sandbox/Dashboard.java
testdata/jennies/builders/initialization_safeguards/JavaBuilders/initialization_safeguards/Options.java
testdata/jennies/builders/initialization_safeguards/JavaBuilders/initialization_safeguards/SomePanel.java
testdata/jennies/builders/known_any/JavaBuilders/known_any/SomeStruct.java
testdata/jennies/builders/nullable_map_assignment/JavaBuilders/nullable_map_assignment/SomeStruct.java
testdata/jennies/builders/panel_builders/JavaBuilders/panelbuilder/Options.java
testdata/jennies/builders/panel_builders/JavaBuilders/panelbuilder/PanelBuilder.java
testdata/jennies/builders/references/JavaBuilders/some_pkg/Person.java
testdata/jennies/builders/struct_fields_as_args_assignment/JavaBuilders/sandbox/SomeStruct.java
testdata/jennies/builders/struct_with_defaults/JavaBuilders/struct_with_defaults/Struct.java

* It adds `Nulls.AS_EMPTY` to set empty values to list and maps.
* It adds `Include.NON_EMPTY` to set these values in the Json when they have any value. It applies for generic (Objects), structs and references.
* Changes `JsonSerialize` with `JsonInclude` because its deprecated 🙃. 
If for any reason, we have problems to don't show initialise objects, we need to initialise them directly in the builder's constructor since there isn't exist an annotation or anything else to setup a non-null object.

Java: Check more kinds to put the proper annotation

---

.github/workflows/grafana-foundation-sdk-diff-preview.yaml

Less noise in the diffs is better.

Ignore more files when calculating the diff preview in CI

---

.github/workflows/ci.yaml
Makefile
README.md
devbox.json

Having both devbox and the Makefile as an entrypoint for targets/commands is confusing.
This PR simplifies that by ensuring that make targets are able to correctly run commands, possibly by decorating them with a `devbox run` if the current shell isn't a devbox one.
As a bonus, the Makefile is now self-documenting.

Make targets detect and use devbox appropriately

---

package_templates/typescript/package.json
repository_templates/typescript/.github/workflows/typescript-release.yaml

Adding provenance information to the NPM package published for the foundation-sdk allows us to publicly establish where a package was built and who published it, which can increase supply-chain security.
See:
* https://docs.npmjs.com/generating-provenance-statements
* https://github.com/grafana/plugin-tools/pull/1127

Add provenance publish config for typescript foundation-sdk package

---

config/compiler/common_passes.yaml
docs/compiler_passes.md
internal/ast/compiler/constants.go
internal/ast/compiler/set_datasource_to_dataquery.go
internal/ast/compiler/set_datasource_to_dataquery_test.go
internal/yaml/compilerpasses.go
schemas/compiler_passes.json

Closes https://github.com/grafana/cog/issues/554
It creates a compiler pass that uses the same `dashboard.DataSourceRef` reference to all dataqueries for the `datasource` field.

Use same datasource reference to all dataqueries

---

config/compiler/kind_registry.yaml

If set to null, this field breaks the Grafana UI. Setting it as optional allows us to omit it in the JSON representation when null.

Set the `piechart.Options.displayLabels` field as optional

---

internal/jennies/golang/templates/runtime/runtime.tmpl
testdata/generated/cog/runtime.go

To determine in which Go struct to unmarshal a dataquery, cog's runtime currently only looks at the datasource details contained in the panel (if it exists). To make the unmarshalling more accurate, we should also look into the query itself since it can hold a DatasourceRef.
This PR only updates the Go jenny, other languages should mimic this behavior.
Relates to #566 and #560

Use the datasource type within queries to unmarshal them

---

.config/ci/php/phpstan.neon
internal/jennies/php/templates/runtime/runtime.tmpl
testdata/generated/cog/variants/variants.go

Use the datasource type within queries to unmarshal them in PHP

---

internal/jennies/python/templates/runtime/runtime.tmpl
testdata/generated/cog/variants/variants.go

Same than #567, but for Python

Use the datasource type within queries to unmarshal them in Python

---

devbox.lock
internal/ast/builder.go
internal/veneers/builder/rules.go

Some builders were missing, turns out because of a bug in the Panel composition veneer.
Example: [`PieChartLegendOptions`](https://github.com/grafana/grafana-foundation-sdk/blob/8c1e08449403c1e93492452bde3362758c0ecd21/go/piechart/types_gen.go#L42) should have a builder

Fix missing builders due to incorrect ComposeDashboardPanel veneer

---

config/compiler/team.yaml
config/foundation_sdk.dev.yaml

Looks like this object was deleted from the kind-registry with v11.2.x by https://github.com/grafana/grafana/pull/90418

Restore missing team.Team object

---

scripts/ci/build-ts.sh

Should help bring CI times down to something more reasonable :crossed_fingers:

Much faster type checking for typescript output in the CI

---

.gitignore

When you generate the sdk or execute Java tests in local, it generates some build folders that we should ignore.

Ignore vendor and Java folders

---

internal/jennies/java/rawtypes.go
internal/jennies/java/registry.go
internal/jennies/java/templates/runtime/dataquery_config.tmpl
internal/jennies/java/templates/runtime/registry.tmpl
internal/jennies/java/templates/runtime/unknown_dataquery.tmpl
internal/jennies/java/templates/runtime/variants.tmpl
internal/jennies/java/templates/types/class.tmpl
internal/jennies/java/tmpl.go
testdata/jennies/builders/dataquery_variant_builder/JavaBuilders/dataquery_variant_builder/Loki.java
testdata/jennies/builders/dataquery_variant_builder/builders_context.json
testdata/jennies/rawtypes/variant_dataquery/JavaRawTypes/variant_dataquery/Query.java

Contributes to: https://github.com/grafana/cog/issues/591
It creates a DataqueryConfig (like panel one), to be able to add any information that we could need in the Registry.
Dataquery now implements `dataqueryName()` function to return the name (useful for the converter's stuff).

Java: Create DataqueryConfig and function to return the dataquery name

---

.github/workflows/ci.yaml
.github/workflows/grafana-foundation-sdk-diff-preview.yaml
devbox.json
devbox.lock

Take advantage of build/result caches to speedup the CI.
Devbox is still the most time-consuming task, not sure how to address it right now but it also installs an absolute bunch of things so... :shrug:

Cache go vendors in CI

---

repository_templates/go/.github/workflows/go-ci.yaml

Surprisingly, `go build` does not, in fact, work on markdown files :shrug:

Fix Go CI in foundation SDK

---

.github/workflows/release.yaml
.gitignore
.goreleaser.yaml
cmd/cli/main.go
devbox.json
devbox.lock

Cog really should start being versioned (even if we stay in v0.0.x for now).
This PR adds a goreleaser config + pipeline to build and publish cog binaries.

Release pipeline

---

repository_templates/php/.github/workflows/php-ci.yaml

See: https://github.com/grafana/grafana-foundation-sdk/actions/runs/11704119766/job/32595882191?pr=354

Bump phpstan memory limit in Foundation SDK PHP CI

---

config/compiler/kind_registry.yaml
config/veneers/dashboard.common.yaml

Fixes grafana/grafana-foundation-sdk#352
There were two problems causing this issue:
* the option that would allow setting data links was omitted when generating builders (I guess I got confused when I saw two `links` fields on panels :shrug:)
* the `links` field is [defined as `[]any` in the original schema](https://github.com/grafana/kind-registry/blob/2aebf33e52bbfb07a94c44b2359f2b00c630a840/grafana/next/core/dashboard/dashboard.cue#L722)

fix: expose a "data links" option in panel builders

---

package_templates/go/docs/Examples.md
package_templates/java/docs/Examples.md
package_templates/php/docs/Examples.md
package_templates/python/docs/Examples.md
package_templates/typescript/docs/Examples.md

To make these examples discoverable from the Foundation SDK website as well.

Add a page dedicated to examples in the Foundation SDK docs

---

internal/jennies/java/builders.go
internal/jennies/java/templates/marshalling/unmarshalling.tmpl
internal/jennies/java/templates/runtime/registry.tmpl
testdata/jennies/builders/dataquery_variant_builder/JavaBuilders/dataquery_variant_builder/Loki.java

It adds null checks for deserialiser templates. The code was assuming that `targets` in panels always exist and Registry wasn't checking that DataqueryConfig could be null too.
Apart of this, I found that some dataquery Builders type was using the class name instead the Dataquery interface. So some of them couldn't be used. I add this fix in this PR because its a small change...
To give you a bit of context: If we have a class `Builder<MyDataquery>` and `MyDataquery` implements `Dataquery` interface, Java doesn't detect it 🤡. So we cannot use it `withTarget` function.

Java: Fix deserializers NPE

---

internal/veneers/builder/rules.go

When a builder veneer returns an error, the message should be descriptive enough to identify which veneer failed.

More descriptive errors in builder veneers

---

helpers.go
internal/jennies/common/importmap.go
internal/jennies/typescript/builder.go
internal/jennies/typescript/builder_test.go
internal/jennies/typescript/imports.go
internal/jennies/typescript/jennies.go
internal/jennies/typescript/rawtypes.go
internal/jennies/typescript/rawtypes_test.go
schemas/pipeline.json

This is especially useful when generating code for a single schema that happens to have a dependency (ie: an import statement) on another, which is already generated.
Example:
```go
package main
import (
"context"
"os"
"github.com/grafana/cog"
)
type codegenTargets struct {
modulePath        string
outputPath        string
cueImportsMap     map[string]string
packagesImportMap map[string]string
}
func main() {
targets := []codegenTargets{
{
modulePath: "../packages/grafana-schema/src/schema/dashboard/v2alpha0/",
outputPath: "../packages/grafana-schema/src/schema/dashboard/v2alpha0/dashboard.gen.ts",
cueImportsMap: map[string]string{
"github.com/grafana/grafana/packages/grafana-schema/src/common": "../packages/grafana-schema/src/common",
},
packagesImportMap: map[string]string{
"common": …
```

Support user-defined packages mapping in TS

---

helpers.go
internal/jennies/typescript/apiref.go
internal/jennies/typescript/builder.go
internal/jennies/typescript/jennies.go
internal/jennies/typescript/rawtypes.go
internal/jennies/typescript/tools.go
internal/jennies/typescript/types.go
schemas/pipeline.json

A `EnumsAsUnionTypes` configuration option is introduced, to generate enums as a union of values instead of using an actual `enum` declaration.
If it is false, an enum will be generated as:
```ts
enum Direction {
Up = "up",
Down = "down",
Left = "left",
Right = "right",
}
```
If it is true, the same enum will be generated as:
```ts
type Direction = "up" | "down" | "left" | "right";
```
This option will be useful in the context of the dashboard V2 schema in grafana/grafana, where enums as disjunctions of concrete values are preferable to actual `enum` declarations.

Support customizing how enums should be generated in Typescript

---

config/foundation_sdk.tests.yaml
internal/jennies/golang/rawtypes.go
internal/jennies/golang/tools.go
testdata/generated/defaults/types_gen.go
testdata/schemas/defaults/defaults.cue

Defaults generation with structs coming from a disjunction was badly broken for Go.
This fix is likely not perfect, but it should allow us to generate Go code from the dashboard v2 schema.

Fix defaults in Go for structs generated from a disjunction

---

internal/jennies/golang/builder.go
internal/jennies/golang/builder_test.go

Relates to #653
Builders sometimes need to perform initializations with _empty values_ before performing the "main" assignment(s).
See https://github.com/grafana/grafana-foundation-sdk/blob/2f6cab6e04b60c66f3bf4314f83e16fe5c8a06fa/go/timeseries/panel_builder_gen.go#L490
This PR ensures that we generate correct _empty values_ for arrays and maps (we don't actually have a schema that needs those... yet: dashboards v2 will).

Fix empty values generated for maps and arrays in go

---

config/veneers/dashboard.common.yaml
internal/veneers/builder/rules.go
internal/veneers/builder/selectors.go
internal/yaml/builder.go

Relates to #653
In order to properly support the Dashboard v2 schema in the Foundation SDK, we need to be able to configure how to compose the various "panel plugins" into self-contained panel builders.
This PR takes the builder veneer that we use today and makes it configurable enough to be used for Dashboard v2 as well.

Make the ComposeDashboardPanel builder veneer configurable

---

.goreleaser.yaml

A changelog sorted alphabetically doesn't make much sense, let's use the order of the commits instead.

Don't sort entries in changelogs

---

config/foundation_sdk.dev.yaml

To have the dev config match the one used by the Foundation SDK

Bump foundation-sdk config

---

internal/veneers/builder/rules.go
internal/veneers/builder/selectors.go
internal/yaml/builder.go
schemas/veneers.json

This veneer was usable only for dashboard panels. With the dashboard v2 schema, it is very likely that we'll need to use it for queries too.
This PR turns the `ComposeDashboardPanel` veneer into a fully generic `Compose` one.

Make the ComposeDashboardPanel builder veneer fully generic

---

internal/jennies/python/templates/builders/nilcheck.tmpl
testdata/jennies/builders/map_index_assignment/PythonBuilder/builders/sandbox.py

These assertions aren't actually valid Python code :|

Do not generate a type assertion for dict values in Python builders nil-check guards

---

internal/jennies/golang/converter.go
internal/jennies/golang/templates/builders/assignment.tmpl
internal/jennies/golang/templates/converters/converter.tmpl
internal/jennies/golang/types.go
internal/jennies/php/templates/builders/assignment.tmpl
internal/jennies/php/typehints.go
internal/jennies/python/templates/builders/assignment.tmpl
internal/jennies/typescript/templates/builder.tmpl
internal/jennies/typescript/types.go
internal/languages/context.go
testdata/jennies/builders/map_of_builders/GoBuilder/map_of_builders/dashboard_builder_gen.go
testdata/jennies/builders/map_of_builders/GoBuilder/map_of_builders/panel_builder_gen.go
testdata/jennies/builders/map_of_builders/GoConverter/map_of_builders/dashboard_converter_gen.go
testdata/jennies/builders/map_of_builders/GoConverter/map_of_builders/panel_converter_gen.go
testdata/jennies/builders/map_of_builders/JavaBuilders/map_of_builders/Dashboard.java
testdata/jennies/builders/map_of_builders/JavaBuilders/map_of_builders/Panel.java
testdata/jennies/builders/map_of_builders/PHPBuilder/src/MapOfBuilders/DashboardBuilder.php
testdata/jennies/builders/map_of_builders/PHPBuilder/src/MapOfBuilders/PanelBuilder.php
testdata/jennies/builders/map_of_builders/PHPConverter/src/MapOfBuilders/DashboardConverter.php
testdata/jennies/builders/map_of_builders/PHPConverter/src/MapOfBuilders/PanelConverter.php
testdata/jennies/builders/map_of_builders/PythonBuilder/builders/map_of_builders.py
testdata/jennies/builders/map_of_builders/TypescriptBuilder/src/mapOfBuilders/dashboardBuilder.gen.ts
testdata/jennies/builders/map_of_builders/TypescriptBuilder/src/mapOfBuilders/panelBuilder.gen.ts
testdata/jennies/builders/map_of_builders/builders_context.json
testdata/jennies/builders/map_of_builders/schema.cue

Given the following schema:
```cue
Panel: {
title: string
}
Dashboard: {
panels: {
[string]: Panel
}
}
```
One would expect a DashboardBuilder to be generated with the following option:
```go
func (builder *DashboardBuilder) Panels(panels map[string]cog.Builder[Panel]) {
// …
}
```
Without this PR, the following option is generated:
```go
func (builder *DashboardBuilder) Panels(panels map[string]Panel) { // note: map of panels, not panel builders
// …
}
```
ToDo:

Maps of builders

---

.github/workflows/ci.yaml

Testing with more or all versions gives us very diminishing returns, so let's focus on a few

Reduce the number of versions of kind-registry to generate in CI

---

internal/jennies/java/rawtypes.go

This has been itching me for a while :sweat_smile: 
In PRs, we often get a preview diff with Java constant definitions flapping around:
```patch
diff --new-file --unidirectional-new-file '--color=never' --unified --recursive '--exclude=.git' '--exclude=gradle.properties' '--exclude=pyproject.toml' '--exclude=package.json' '--exclude=*.md' /tmp/foundation-workspace-main/foundation-sdk/java/src/main/java/com/grafana/foundation/common/Constants.java /tmp/foundation-workspace-current/foundation-sdk/java/src/main/java/com/grafana/foundation/common/Constants.java
--- /tmp/foundation-workspace-main/foundation-sdk/java/src/main/java/com/grafana/foundation/common/Constants.java	2025-01-09 11:56:53.298994454 +0000
+++ /tmp/foundation-workspace-current/foundation-sdk/java/src/main/java/com/grafana/fo …
```

Sort constants in java to ensure a deterministic output

---

internal/jennies/php/rawtypes.go

Otherwise a placeholder function might be defined :|

Ensure template functions are consistently setup in PHP rawtypes jenny

---

internal/jennies/typescript/builder.go
internal/jennies/typescript/builder_test.go
internal/jennies/typescript/index.go
internal/jennies/typescript/jennies.go
internal/jennies/typescript/rawtypes.go
internal/jennies/typescript/rawtypes_test.go
internal/jennies/typescript/runtime.go
internal/jennies/typescript/runtime_test.go
internal/tools/types.go
schemas/pipeline.json

Because there is no reason to force the generated TS code to live under a `src` directory.

Configurable filepath prefix in typescript

---

helpers.go
internal/jennies/golang/builder_test.go
internal/jennies/golang/converter_test.go
internal/jennies/golang/jennies.go
internal/jennies/golang/rawtypes_test.go
internal/jennies/golang/templates/types/disjunction_of_refs.json_unmarshal.tmpl
internal/jennies/golang/templates/types/disjunction_of_refs.strict.json_unmarshal.tmpl
internal/jennies/golang/tmpl.go
internal/jennies/golang/types.go
schemas/pipeline.json

Will be useful in codebases that don't support `any` (or prefer `interface{}`).

Add an option allowing to emit `any` types as `interface{}` in Go

---

internal/jsonschema/generator.go
internal/jsonschema/generator_test.go

Without this fix, cog can't properly parse its own [codegen pipeline schema](https://github.com/grafana/cog/blob/main/schemas/pipeline.json) :scream: 
(not that we need to parse it, but still)

Fix array parsing for jsonschema draft 2020

---

internal/jennies/common/templatehelpers.go
internal/languages/context.go
internal/languages/context_test.go

Consider the following dummy schema:
```cue
Variable: QueryVariable | DatasourceVariable // ← no builder generated for type aliases
QueryVariable: { ... } // ← builder generated
DatasourceVariable: { ... } // ← builder generated
Dashboard: {
variables: [...Variable]
}
```
When generating a builder for the Dashboard object, cog doesn't detect that the `variables()` option should accept a list of `Builder<Variable>` as argument.
This PR fixes that :)

Builders disjunctions

---

internal/simplecue/generator.go
internal/simplecue/generator_test.go
internal/simplecue/referenceresolver.go
testdata/simplecue/nested_disjunctions/GenerateAST/ir.json
testdata/simplecue/nested_disjunctions/schema.cue

Overriding the package name via the codegen pipeline doesn't work for cue schemas.
This PR addresses that.

Fix package override via configuration in cue

---

docs/reference/schema_transformations.md
internal/ast/compiler/constant_to_enum.go
internal/ast/compiler/constant_to_enum_test.go
internal/ast/compiler/types.go
internal/yaml/compilerpasses.go
schemas/compiler_passes.json

The `ConstantToEnum` compiler pass turns `string` constants into an enum definition with a
single member.
This is useful to "future-proof" a schema where a type can have a single value for now but is expected to allow more in the future.
Example: https://github.com/grafana/grafana/blob/7564ce8ce1cd2ed0a0a8bdb72f6221767e1d5321/packages/grafana-schema/src/schema/dashboard/v2alpha0/dashboard.schema.cue#L469
(we can and will adjust the original schema, but this pass is still a useful one to have)

Compiler pass/constant to enum

---

config/foundation_sdk.dev.yaml

Was added in the Foundation SDK via https://github.com/grafana/grafana-foundation-sdk/pull/575, this PR is just to have the dev codegen pipeline used by cog align with the one in the Foundation SDK

Add `datasource` schema

---

.github/workflows/grafana-foundation-sdk-diff-preview.yaml

I often get confused by the diff displayed in the PRs, only to remember that we generated that diff not based on the output of `config/foundation_sdk.dev.yaml` but on the actual Foundation SDK config instead.
I think it makes more sense to show a diff based on `config/foundation_sdk.dev.yaml` within cog.

Show diff of the SDK dev codegen pipeline in PRs

---

internal/ast/compiler/hint_object.go

Should help getting rid of these annoyingly flaky diffs: https://github.com/grafana/cog/pull/725#issuecomment-2613554430

Ensure a consistent pass trail for the HintObject pass

---

internal/jennies/python/builder.go
internal/jennies/python/templates/builders/assignment.tmpl
internal/jennies/python/tmpl.go
testdata/jennies/builders/builder_delegation_in_disjunction/PythonBuilder/builders/builder_delegation_in_disjunction.py

This adds/fixes support for disjunctions of scalar types and builders in Python.
Ex: `str | Builder[Something]`

Better handling of disjunctions in builders for python

---

internal/veneers/builder/rules.go
internal/veneers/option/actions.go
internal/veneers/types.go
schemas/veneers.json

This PR tweaks the `AddOption` builder veneer to make it easier to use.
See https://github.com/grafana/grafana-foundation-sdk/pull/598 where I use this veneer to add a few convenience options to add overrides to panels.

Add support for setting comments and arguments in AddOption builder veneer

---

examples/_go/disk.go
examples/java/src/main/java/test/Disk.java
examples/php/src/Monitoring/Disk.php
examples/python/raspberry/disk.py
examples/typescript/disk.ts

Now that we have <sub>slightly</sub> cleaner ways of defining overrides, let's reflect that in the examples!

Cleanup override-related code in examples

---

internal/veneers/option/actions.go
internal/veneers/option/actions_test.go
internal/veneers/option/rules.go
internal/yaml/option.go
schemas/veneers.json

In #722, it turns out that we need to apply this veneer on an option that has several arguments. This PR makes the veneer generic-enough to support this use-case

Update the DisjunctionAsOptions option veneer to work on any argument

---

internal/veneers/builder/rules.go
internal/yaml/builder.go
schemas/veneers.json

This is needed to support both dashboard & dashboardv2, since both of these packages need to perform similar composition transformations for panels.

Support preserving the original builders in ComposeBuilders veneer

---

Makefile
internal/veneers/builder/rules.go

These assignments - when they exist - should be copied over since they might initialize fields with important values.

Copy constant assignment from source builders in MergeInto builder veneer

---

cmd/cli/inspect/command.go

This PR extends the `cog inspect` command to support inspecting "converters" intermediate representations.

Support inspecting the "converters" IR

---

internal/simplecue/generator.go
testdata/simplecue/refs/GenerateAST/ir.json

Relates to grafana/grafana#99966
One issue highlighted by the PR above comes from cog not being always able to discover objects within a schema (especially objects defined outside of the cue value given as input to cog).
To fix that, the CUE parser now follows references and parses the objects they point to.

Better detection of "out-of-root" types in CUE

---

internal/codegen/pipeline.go
internal/codegen/run.go

Otherwise they're not really final, are they?

Final compiler passes should be applied after language-specific passes

---

helpers.go
internal/codegen/cue.go
internal/simplecue/generator.go

This is useful when using cog as a library, in which case the output it generates is meant to be self-contained.

Support optionally inlining external references in CUE

---

internal/ast/compiler/flatten_disjunctions.go
internal/ast/compiler/flatten_disjunctions_test.go
internal/jennies/python/rawtypes.go
testdata/jennies/rawtypes/struct_with_complex_fields/PythonRawTypes/models/struct_complex_fields.py

This PR addresses two issues related to disjunctions in Python:
* the code generated for disjunction parameters in constructors was incorrect
* the "flatten disjunctions" compiler pass incorrectly flattened disjunction of strings + constants

Fix some disjunctions bugs in Python

---

internal/ast/builder.go
internal/veneers/builder/rules.go
internal/yaml/builder.go
internal/yaml/option.go

It is more intuitive to refer to builders by their name, instead of the name of the object they're building.
Moreover, this will allow us to use the "merge into" veneer on more builders

Select builders to "merge into" by name instead of object

---

internal/yaml/veneers.go
internal/yaml/veneers_test.go

When veneers can't be loaded, the error message should contain the file that caused the error.

Better error reporting in veneer yaml loading

---

examples/_go/main.go
examples/java/src/main/java/test/Main.java
examples/php/index.php
examples/python/main.py
examples/typescript/index.ts

https://github.com/grafana/grafana/commit/d1dee968c38791ed8fc4e1ae71229064b0e5bd96#diff-abdfd6a9318ae27ef245c1da7557b327ca1e4e6a10ee220b76e162c6865eeb28 removed the time_options field from dashboards :shrug:

Update examples for changes in kind-registry next

---

config/foundation_sdk.dev.yaml
config/foundation_sdk.tests.yaml
helpers.go
internal/jennies/golang/jennies.go
internal/jennies/golang/jsonmarshalling.go
internal/jennies/golang/rawtypes.go
internal/jennies/golang/rawtypes_test.go
internal/jennies/golang/strictjson.go
internal/jennies/java/jennies.go
internal/jennies/java/jsonmarshalling.go
internal/jennies/java/rawtypes_test.go
internal/jennies/php/jennies.go
internal/jennies/php/rawtypes.go
internal/jennies/php/rawtypes_test.go
internal/jennies/python/jennies.go
internal/jennies/python/rawtypes.go
internal/jennies/python/rawtypes_test.go
schemas/pipeline.json
schemas/veneers.json

This PR makes the generation of JSON (un)marshalling-related code configurable.
Note: to be consistent with other `generate_*` configuration options, this effectively introduces a BC-break. We'll need to explicitly enable this in the codegen pipeline used for the Foundation SDK.

Configurable JSON marshalling generation

---

internal/veneers/builder/rules.go
internal/yaml/builder.go

`DefaultToConstant` was an action added to set missing defaults in the builder. It happens in Java in Go because we didn't have default constructors that set defaults information.
After move all defaults into default constructors in types, we don't have to deal with this issue anymore, so we don't need the action.
Closes https://github.com/grafana/cog/issues/552
Depends on: https://github.com/grafana/grafana-foundation-sdk/pull/638

Delete default to constant veneer

---

docs/reference/schema_transformations.md
internal/ast/compiler/add_object.go
internal/yaml/compilerpasses.go
schemas/compiler_passes.json

Objects can have comments, yet the `add_objects` compiler pass didn't support their definition.
This PR addresses that.

Support defining comments in "add_object" compiler pass

---

internal/jennies/golang/jennies.go
schemas/pipeline.json

If the generated Go code isn't valid, post-formatting will fail and prevent the code from being written to disk.
To make debugging these cases easier, this PR adds an option to disable this formatting.

Support disabling post-formatting in Go jenny

---

internal/semver/semver.go

To be able to parse things like: https://github.com/grafana/grafana-foundation-sdk/blob/30676a122045f1c47a058079fc5b52d70e86010a/scripts/release-version.sh#L151-L153

Make semver.ParseTolerant() even more tolerant

---

internal/jennies/golang/rawtypes.go
internal/jennies/golang/tools.go
testdata/generated/equality/types_gen.go
testdata/generated/validation/types_gen.go
testdata/jennies/rawtypes/constraints/GoRawTypes/constraints/types_gen.go
testdata/jennies/rawtypes/field_with_struct_with_defaults/GoRawTypes/defaults/types_gen.go
testdata/jennies/rawtypes/struct_with_complex_fields/GoRawTypes/struct_complex_fields/types_gen.go

When the schema indicates a field as required (or at least "not optional"), we need to make sure it has a value. We already did that in most cases, but somehow not for arrays and maps.

Generate an empty value for required arrays/maps in Go

---

helpers.go
helpers_test.go

This PR adds the ability to output OpenAPI JSON from the `SchemasToTypesPipline` type, using the `GenerateOpenAPI` method. Method is named `GenerateOpenAPI` rather than `OpenAPI` (like the go and TypeScript variants), as I wanted to make sure it was distinct from a possible future input type of OpenAPI (like the current `CUEValue` method that sets the input). 
OpenAPI output can be used by the [grafana-app-sdk](https://github.com/grafana/grafana-app-sdk) instead of CUE's openAPI encoder to allow the app-sdk to parse recursive types from CUE (which CUE's openAPI encoder fails on).

Add OpenAPI output to the SchemaToTypesPipeline

---

internal/jennies/python/templates/runtime/builder.tmpl

As of currently, the `grafana_foundation_sdk` does not [pass typechecking in its example](https://github.com/grafana/grafana-foundation-sdk/blob/main/.mkdocs/docs/index.md).
This is because the `with_target` function expects a `cogbuilder.Builder[cogvariants.Dataquery]` type to be passed, but the prometheus query returns a Dataquery, which inherits from `cogbuilder.Builder[prometheus.Dataquery]`.
This doesn't type check, because they are not the same type, and the generic type is not marked as [covariant](https://peps.python.org/pep-0483/#covariance-and-contravariance). 
Given the implementation of `build`, I believe the type is in practice covariant.
Marking it as such fixes the type checking of the dashboard.

Python: Adjust the builder's contained type to be covariant

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/grafana-foundation-sdk-diff-preview.yaml
.github/workflows/release.yaml

Fixing findings from running zizmor against the CI configurations. After this is merged in we can re-enable CI for the repo.
There is a potential that the permissions for docs is not properly done, but we can fix that in the future.

Fix CI security recommendations

---

internal/jennies/java/apiref.go

The reference for options in Java currently show incorrect signature: even when options accept builders, the documentation tells otherwise.

Fix generated options reference in java

---

internal/jennies/java/builder.go
internal/jennies/java/rawtypes.go
internal/jennies/java/types.go

In some cases, java constructors would rely on builders to get the empty value for a field: this is a bug :|

Java type constructors shouldn't use builders

---

internal/ast/compiler/disjunctions.go
internal/ast/hints.go
internal/ast/types.go
internal/jennies/golang/jsonmarshalling.go
internal/jennies/golang/templates/types/disjunction_of_scalars_and_refs.json_marshal.tmpl
internal/jennies/java/jsonmarshalling.go
internal/jennies/java/rawtypes.go
testdata/jennies/rawtypes/disjunctions/GoRawTypes/disjunctions/types_gen.go
testdata/jennies/rawtypes/disjunctions/JavaRawTypes/disjunctions/BoolOrRef.java
testdata/jennies/rawtypes/struct_with_complex_fields/GoRawTypes/struct_complex_fields/types_gen.go
testdata/jennies/rawtypes/struct_with_complex_fields/JavaRawTypes/struct_complex_fields/StringOrSomeOtherStruct.java

Closes https://github.com/grafana/cog/issues/813
We were skipping the Marshal functions when we generate disjunctions with mixed refs and scalars. So disjunctions that have more than one type, are marked as `HintDisjunctionOfScalarsAndRefs` to be used where we need it.
Edit: Looks like that the bug was also in Java 😄

Go: Add missing Marshal functions for disjunctions with mixed scalars and references

---

internal/jennies/golang/jsonmarshalling.go
internal/jennies/golang/templates/types/disjunction_of_refs.json_marshal.tmpl
internal/jennies/golang/templates/types/disjunction_of_refs.json_unmarshal.tmpl
internal/jennies/golang/templates/types/disjunction_of_scalars.json_marshal.tmpl
internal/jennies/golang/templates/types/disjunction_of_scalars_and_refs.json_marshal.tmpl

Some templates were adding `fmt` import when they don't need it.

Go: Remove unused `fmt` import from marshal/unmarshal templates

---

internal/openapi/generator.go

`cog generate` was failing with my openapi schema because of an enum without a type:
```yaml
NullEnum:
enum:
- null
```
Changing that to this fixed the issue and types were generated:
```yaml
NullEnum:
enum:
- null
type: string
```
There is a comment in `internal/openapi/generator.go` that alludes to this edge case
This PR adds code to handle the situation although I'm not sure if it's the correct way to handle it or not?

fix: handle case where Type.Slice() could be null

---

examples/java/src/main/java/test/Common.java
examples/java/src/main/java/test/Disk.java
examples/java/src/main/java/test/Logs.java
examples/java/src/main/java/test/Memory.java
examples/java/src/main/java/test/Network.java
internal/jennies/java/builder.go
testdata/jennies/builders/foreign_builder/JavaBuilder/builder_pkg/BuilderPkgSomeStructBuilder.java
testdata/jennies/builders/package-with-dashes/JavaBuilder/builderpkg/BuilderPkgSomeStructBuilder.java

When we are working with composables, we could have conflicts using the same names in their generation.
When we detect that `builder.For.SelfRef.ReferredPkg != builder.Package` is different, it means that it's a composable. `ReferredPkg` indicates the composed package name, and `builder.Package` the one of the class generated. `builder.For.SelfRef.ReferredType` and `builder.Name` could be the same (it happens for panels)
When we have multiple composables for one schema, returning the package only, could be the same. Instead, it composes this package with the composed class name to generating unique names.

Java: Avoid to generate duplicate classes with the same name

---

internal/jennies/golang/tmpl.go
internal/jennies/java/builder_test.go
internal/jennies/java/jennies.go
internal/jennies/java/rawtypes.go
internal/jennies/java/rawtypes_test.go
internal/jennies/java/templates/types/class.tmpl
internal/jennies/java/tmpl.go
internal/jennies/php/builder_test.go
internal/jennies/php/converter_test.go
internal/jennies/php/jennies.go
internal/jennies/php/rawtypes_test.go
internal/jennies/php/tmpl.go
internal/jennies/python/builder_test.go
internal/jennies/python/jennies.go
internal/jennies/python/rawtypes_test.go
internal/jennies/python/tmpl.go
internal/jennies/typescript/builder_test.go
internal/jennies/typescript/jennies.go
internal/jennies/typescript/rawtypes_test.go
internal/jennies/typescript/tmpl.go

Java missing the way to identify if exist custom templates to add more functions to rawtypes.
And it also has a small refactor so all languages follow the same structure.

Java: Fix template parsing

---

internal/jennies/golang/rawtypes.go
internal/jennies/golang/templates/types/struct_equality_method.tmpl
internal/simplecue/utils.go
testdata/generated/equality/types_gen.go
testdata/jennies/rawtypes/disjunctions/GoRawTypes/disjunctions/types_gen.go
testdata/jennies/rawtypes/struct_with_scalar_fields/GoRawTypes/basic/types_gen.go
testdata/schemas/equality/equality.cue

We weren't parsing byte values with cue and we were using `!=` to check the equality of `[]byte` generating invalid code. 
This PR adds the missing value in cue and uses `bytes.Equal` function to compare bytes.

Go: Fix []byte in equal function

---

internal/simplecue/generator.go

Generating manifest fails in app-sdk because constant reference objects are missing. For any reason, when the scope of the cue value changes (e.g. unifying values), sometimes the parser skips the constant references.
I saw that we have similar behaviour when we detect that a field is a reference and we "skip" some objects, we force to add them 🤷🏼‍♀️.
This change fixes manifest generation.

Add constant reference into objects if the parser skipped for any reason

---

internal/ast/builder.go
internal/jennies/golang/rawtypes.go
internal/jennies/golang/templates/types/struct_equality_method.tmpl
internal/jennies/golang/types.go
internal/jennies/typescript/rawtypes.go
testdata/jennies/rawtypes/constant_reference_as_default/GoRawTypes/constant_reference_as_default/types_gen.go
testdata/jennies/rawtypes/constant_reference_as_default/JSONSchema/constant_reference_as_default.jsonschema.json
testdata/jennies/rawtypes/constant_reference_as_default/JavaRawTypes/constant_reference_as_default/Constants.java
testdata/jennies/rawtypes/constant_reference_as_default/JavaRawTypes/constant_reference_as_default/MyStruct.java
testdata/jennies/rawtypes/constant_reference_as_default/OpenAPI/constant_reference_as_default.openapi.json
testdata/jennies/rawtypes/constant_reference_as_default/PHPRawTypes/src/ConstantReferenceAsDefault/Constants.php
testdata/jennies/rawtypes/constant_reference_as_default/PHPRawTypes/src/ConstantReferenceAsDefault/MyStruct.php
testdata/jennies/rawtypes/constant_reference_as_default/PythonRawTypes/models/constant_reference_as_default.py
testdata/jennies/rawtypes/constant_reference_as_default/TypescriptRawTypes/src/constantReferenceAsDefault/types.gen.ts
testdata/jennies/rawtypes/constant_reference_as_default/ir.json
testdata/jennies/rawtypes/constant_reference_as_default/schema.cue

Edited!!!
* **Go**: It fixes the fields declared as ConstantReferences when they are optional. We were missing to set them as nullable, making the equal function to fail.
* **Typescript**: We weren't setting the ConstantReference value in the constructor when it was optional.
* **All builders**: We were skipping the options declared as ConstantReference and they were used as fixed value. The option now is available only if the field is optional.

Fix Constant References null checks

---

cmd/cli/inspect/command.go
internal/codegen/pipeline.go
internal/codegen/run.go
internal/codegen/transforms.go
internal/jennies/golang/converter.go
internal/jennies/java/converter.go
internal/jennies/php/converter.go
internal/languages/context.go
internal/languages/converter.go
internal/yaml/converter_config.go

The Runtime configuration to detect that the panels needs to use runtime code ([extra code added in Foundation-SDK by configuration](https://github.com/grafana/grafana-foundation-sdk/blob/main/.cog/templates/go/extra/cog/runtime.go)) is hardcoded.
For V2 we need the same for `VizConfigKind` to be able to set the proper panel if exists.
You can see the current behaviour [here](https://github.com/grafana/grafana-foundation-sdk/blob/v11.6.x%2Bcog-v0.0.x/go/dashboard/dashboard_converter_gen.go#L344) if you need to check how its the result.
If we want to release a new version of Foundation-SDK with this version, it needs to adds the converters configuration to have the previous result.

Converters: Modify runtime output by configuration.

---

internal/jennies/common/templatehelpers.go
internal/jennies/golang/rawtypes.go
internal/jennies/golang/tmpl.go
internal/jennies/java/tmpl.go
internal/jennies/php/tmpl.go
internal/jennies/python/tmpl.go
internal/jennies/typescript/tmpl.go

For converters, in Go at least, each panel has a configuration function that returns the proper converter for that panel. For example, [this one](https://github.com/grafana/grafana-foundation-sdk/blob/v11.6.x%2Bcog-v0.0.x/go/bargauge/types_gen.go#L327-L333). The code is generated using a [template](https://github.com/grafana/grafana-foundation-sdk/blob/main/.cog/templates/go/overrides/schema_variant_panelcfg.tmpl#L61-L65). 
For V2 schemas, we have to cast the input received into `dashboardv2beta1.VizConfigKind`, but adding this code isn't enough since the template is used in all versions of Grafana and it will only work with Grafana 12+. Something like that:
```go
if panel, ok := inputPanel.(*dashboardv2beta1.VizConfigKind); ok {
return VisualizationConverter(*panel)
}
```
So this PR adds …

Converters: Add function for templates to check if an object exists
