grafana/cog

.github/dependabot.yaml

To help us keep track of our dependencies and their updates :)

Setup dependabot

---

internal/jsonschema/generator.go
internal/jsonschema/generator_test.go
testdata/jsonschema/anyof_object.txtar
testdata/jsonschema/anyof_struct_field.txtar
testdata/jsonschema/array_any.txtar
testdata/jsonschema/basic_object.txtar
testdata/jsonschema/consts.txtar
testdata/jsonschema/defaults.txtar
testdata/jsonschema/enum.txtar
testdata/jsonschema/influxdbquery.txtar
testdata/jsonschema/oneof_object.txtar
testdata/jsonschema/oneof_struct_field.txtar
testdata/jsonschema/ref_struct_field.txtar

Bootstrap a txtar-based test suite for the jsonschema parser

Bootstrap jsonschema test suite

---

docs/releasing-grafana-foundation-sdk.md
scripts/release-version.sh

A slightly prettier version of my own notes on using our release script.

Bootstrap some docs on how to release to grafana-sdk-foundation

---

internal/jsonschema/generator.go
testdata/jsonschema/allof_object.txtar

Parsing `allOf` should allow this parser to be *good enough* to consider #172 done

Parse allOf as an intersection in jsonschema

---

internal/jennies/typescript/rawtypes.go

The title pretty much says it all.
Default values defined at struct level can include values that are defined as an enum. In Typescript, we need to generate code that reflects that.
Example cue schema:
```cue
tooltip: HeatmapTooltip | *{
mode:           ui.TooltipDisplayMode & (*"single" | _)
yHistogram:     false
showColorScale: false
}
```
Resulting code:
```typescript
// Before
tooltip: { mode: "single", yHistogram: false, showColorScale: false, },
// After
tooltip: { mode: common.TooltipDisplayMode.Single, yHistogram: false, showColorScale: false, },
```

Fix default value generation for enum members in Typescript

---

config/dashboard.variables.veneers.common.yaml
internal/ast/compiler/constants.go
internal/ast/compiler/dashboard.go

This change is meant to be temporary and reverted when https://github.com/grafana/grafana/pull/79236 is merged.

Add a few missing fields `dashboard.VariableModel`

---

internal/ast/compiler/constants.go
internal/ast/compiler/dashboard.go

Since https://github.com/grafana/grafana/pull/79236 was merged

Remove the temporary dashboard.VariableModel modifications introduced by #216

---

internal/orderedmap/map.go
internal/orderedmap/map_test.go

This PR adds a few functions to make working with our ordered map implementation a bit easier.
They're not used anywhere yet, but I'll need these in PRs that will be coming soon :) (in which I'll slightly refactor the way we store objects and struct fields in our IR)

Orderedmap utils

---

internal/jsonschema/generator.go

JSONSchemas clearly identify the "root" type in the schema, we can use that fact to propagate information like the "schema variant" onto that type.
This makes identifying dataqueries and panels explicit, rather than being done implicitly in a compiler pass.

Propagate variant metadata to root objects in JSONSchema

---

cmd/cli/loaders/kindsyscomposable.go
config/compiler/common_passes.yaml
internal/ast/compiler/constants.go
internal/ast/compiler/schema_set_identifier.go
internal/veneers/builder/rules.go
internal/yaml/compilerpasses.go

Relates to https://github.com/grafana/grafana-foundation-sdk/issues/43
See [counterpart in grafonnet](https://github.com/grafana/grafonnet/blob/main/generator/utils.libsonnet#L38-L54)

Fix composable kinds identifiers for "irregular" kinds

---

internal/jennies/python/templates/builders/assignment.tmpl
testdata/jennies/builders/builder_delegation/PythonBuilder/builders/builder_delegation.py
testdata/jennies/builders/composable_slot/PythonBuilder/builders/composable_slot.py

Follow-up for #263, in Python this time.

Support arbitrary nesting levels of arrays of builders in Python

---

internal/jennies/python/templates/builders/assignment.tmpl
internal/jennies/typescript/templates/builder.tmpl
testdata/jennies/builders/builder_delegation/PythonBuilder/builders/builder_delegation.py
testdata/jennies/builders/builder_delegation/TypescriptBuilder/src/builder_delegation/dashboard_builder_gen.ts
testdata/jennies/builders/composable_slot/PythonBuilder/builders/composable_slot.py
testdata/jennies/builders/composable_slot/TypescriptBuilder/src/composable_slot/lokibuilder_builder_gen.ts

Follow-up for #263, in Typescript this time.

Ts nested builders of builders

---

internal/jennies/golang/templates/types/disjunction_of_refs.json_marshal.tmpl
internal/jennies/golang/templates/types/disjunction_of_scalars.json_marshal.tmpl
testdata/jennies/rawtypes/disjunctions/GoJSONMarshalling/disjunctions/types_json_marshalling_gen.go
testdata/jennies/rawtypes/package-with-dashes/GoJSONMarshalling/withdashes/types_json_marshalling_gen.go
testdata/jennies/rawtypes/struct_with_complex_fields/GoJSONMarshalling/struct_complex_fields/types_json_marshalling_gen.go

Custom marshal functions need to return valid JSON.

Fix go custom marshal function to correctly handle null cases

---

.github/workflows/ci.yaml
internal/jennies/python/rawtypes.go
testdata/jennies/rawtypes/variant_dataquery/PythonRawTypes/models/variant_dataquery.py

Lint generated Python artifacts in the CI.

Lint generated python code in CI

---

package_templates/python/README.md

Same than #317 and #318, but for Python

Python readme examples

---

config/veneers/dashboard.veneers.common.yaml

Let's make dashboard annotations easier to define.

Define a few veneers for dashboard annotations

---

internal/jennies/typescript/templates/builder.tmpl
testdata/jennies/builders/anonymous_struct/TypescriptBuilder/src/anonymousStruct/someStructBuilder.gen.ts
testdata/jennies/builders/array_append/TypescriptBuilder/src/sandbox/someStructBuilder.gen.ts
testdata/jennies/builders/basic_struct/TypescriptBuilder/src/basicStruct/someStructBuilder.gen.ts
testdata/jennies/builders/basic_struct_defaults/TypescriptBuilder/src/basicStructDefaults/someStructBuilder.gen.ts
testdata/jennies/builders/builder_delegation/TypescriptBuilder/src/builderDelegation/dashboardBuilder.gen.ts
testdata/jennies/builders/builder_delegation/TypescriptBuilder/src/builderDelegation/dashboardLinkBuilder.gen.ts
testdata/jennies/builders/builder_delegation_in_disjunction/TypescriptBuilder/src/builderDelegationInDisjunction/dashboardBuilder.gen.ts
testdata/jennies/builders/builder_delegation_in_disjunction/TypescriptBuilder/src/builderDelegationInDisjunction/dashboardLinkBuilder.gen.ts
testdata/jennies/builders/builder_delegation_in_disjunction/TypescriptBuilder/src/builderDelegationInDisjunction/externalLinkBuilder.gen.ts
testdata/jennies/builders/composable_slot/TypescriptBuilder/src/composableSlot/lokiBuilderBuilder.gen.ts
testdata/jennies/builders/constant_assignment/TypescriptBuilder/src/sandbox/someStructBuilder.gen.ts
testdata/jennies/builders/constraints/TypescriptBuilder/src/constraints/someStructBuilder.gen.ts
testdata/jennies/builders/constructor_argument/TypescriptBuilder/src/sandbox/someStructBuilder.gen.ts
testdata/jennies/builders/constructor_initializations/TypescriptBuilder/src/constructorInitializations/somePanelBuilder.gen.ts
testdata/jennies/builders/dataquery_variant_builder/TypescriptBuilder/src/dataqueryVariantBuilder/lokiBuilderBuilder.gen.ts
testdata/jennies/builders/envelope_assignment/TypescriptBuilder/src/sandbox/dashboardBuilder.gen.ts
testdata/jennies/builders/foreign_builder/TypescriptBuilder/src/builderPkg/someNiceBuilderBuilder.gen.ts
testdata/jennies/builders/initialization_safeguards/TypescriptBuilder/src/initializationSafeguards/somePanelBuilder.gen.ts
testdata/jennies/builders/known_any/TypescriptBuilder/src/knownAny/someStructBuilder.gen.ts
testdata/jennies/builders/nullable_map_assignment/TypescriptBuilder/src/nullableMapAssignment/someStructBuilder.gen.ts
testdata/jennies/builders/package-with-dashes/TypescriptBuilder/src/builderPkg/someNiceBuilderBuilder.gen.ts
testdata/jennies/builders/properties/TypescriptBuilder/src/properties/someStructBuilder.gen.ts
testdata/jennies/builders/references/TypescriptBuilder/src/somePkg/personBuilder.gen.ts
testdata/jennies/builders/struct_fields_as_args_assignment/TypescriptBuilder/src/sandbox/someStructBuilder.gen.ts
testdata/jennies/builders/struct_with_defaults/TypescriptBuilder/src/structWithDefaults/nestedStructBuilder.gen.ts
testdata/jennies/builders/struct_with_defaults/TypescriptBuilder/src/structWithDefaults/structBuilder.gen.ts

See https://github.com/grafana/grafana-foundation-sdk/pull/80#pullrequestreview-2007059175

Open Typescript builders for extension

---

package_templates/typescript/README.md

Because less code is better code.

Simplify the custom panel example in Typescript

---

internal/jennies/python/builder.go
internal/jennies/python/templates/builders/assignment.tmpl
internal/jennies/python/templates/builders/builder.tmpl
package_templates/python/README.md
testdata/jennies/builders/array_append/PythonBuilder/builders/sandbox.py
testdata/jennies/builders/basic_struct/PythonBuilder/builders/basic_struct.py
testdata/jennies/builders/basic_struct_defaults/PythonBuilder/builders/basic_struct_defaults.py
testdata/jennies/builders/builder_delegation/PythonBuilder/builders/builder_delegation.py
testdata/jennies/builders/builder_delegation_in_disjunction/PythonBuilder/builders/builder_delegation_in_disjunction.py
testdata/jennies/builders/composable_slot/PythonBuilder/builders/composable_slot.py
testdata/jennies/builders/constant_assignment/PythonBuilder/builders/sandbox.py
testdata/jennies/builders/constraints/PythonBuilder/builders/constraints.py
testdata/jennies/builders/constructor_argument/PythonBuilder/builders/sandbox.py
testdata/jennies/builders/constructor_initializations/PythonBuilder/builders/constructor_initializations.py
testdata/jennies/builders/dataquery_variant_builder/PythonBuilder/builders/dataquery_variant_builder.py
testdata/jennies/builders/envelope_assignment/PythonBuilder/builders/sandbox.py
testdata/jennies/builders/foreign_builder/PythonBuilder/builders/builder_pkg.py
testdata/jennies/builders/initialization_safeguards/PythonBuilder/builders/initialization_safeguards.py
testdata/jennies/builders/known_any/PythonBuilder/builders/known_any.py
testdata/jennies/builders/nullable_map_assignment/PythonBuilder/builders/nullable_map_assignment.py
testdata/jennies/builders/package-with-dashes/PythonBuilder/builders/builder-pkg.py
testdata/jennies/builders/properties/PythonBuilder/builders/properties.py
testdata/jennies/builders/references/PythonBuilder/builders/some_pkg.py
testdata/jennies/builders/struct_fields_as_args_assignment/PythonBuilder/builders/sandbox.py
testdata/jennies/builders/struct_with_defaults/PythonBuilder/builders/struct_with_defaults.py

Same than #321, but for Python.

Open Python builders for extension

---

cmd/cli/generate/command.go
cmd/cli/inspect/command.go
cmd/cli/loaders/config.go
cmd/cli/loaders/cue.go
cmd/cli/loaders/jsonschema.go
cmd/cli/loaders/openapi.go
cmd/cli/loaders/tools.go
internal/jsonschema/generator_test.go
internal/openapi/generator.go
internal/openapi/generator_test.go
internal/testutils/jennytestsuite.go

This PR exposes the "schema filter" compilation pass introduced in #334 via the codegen configuration file.

Support filtering input schemas by allowed objects

---

internal/jennies/golang/jsonmarshalling.go
testdata/jennies/rawtypes/dashboard/GoJSONMarshalling/dashboard/types_json_marshalling_gen.go

Some panel's JSON definition do not include a `custom` field in their definition (the example I found seemed to be a timeseries panel that was auto-migrated from a graph one).
The unmarshalling process shouldn't assume that there always will be a `custom` field.

More defensive unmarshalling of panels in Go

---

internal/ast/compiler/disjunctions_of_anonymous_to_explicit.go
internal/ast/compiler/disjunctions_of_anonymous_to_explicit_test.go
internal/ast/compiler/hint_object.go
internal/ast/compiler/hint_object_test.go
internal/ast/compiler/retype_field.go
internal/ast/compiler/retype_object.go
internal/yaml/compilerpasses.go

A collection of various improvements to compiler passes: new ones, and more passes exposed in the yaml config file.
Some context: these changes are useful to support alerting resources (see #348)

Compiler pass/moar

---

config/veneers/dashboard.common.yaml
internal/veneers/builder/rules.go
internal/yaml/builder.go

This option was incorrectly excluded

Expose the FieldConfig.Defaults.Color option in panels

---

internal/simplecue/generator.go

This explains why dataquery types don't have comments :facepalm:

Fix cue parser to parse comments in CUE variant envelopes

---

config/compiler/testdata_passes.yaml
config/foundation_sdk.dev.yaml
config/foundation_sdk.yaml
internal/yaml/compilerpasses.go

Load correct schemas for testdata queries and Grafana >= v11

---

internal/ast/schema.go

Fix duplicated schema.Locate() definition

---

internal/ast/compiler/dataquery_identification.go

When a dataquery is successfully identified by the `DataqueryIdentification` compiler pass, it should update the schema metadata to reflect that fact.
Possible alternative to #398

Update the schema metadata in DataqueryIdentification

---

internal/jennies/golang/types.go
testdata/jennies/rawtypes/disjunctions/GoRawTypes/disjunctions/types_gen.go
testdata/jennies/rawtypes/struct_with_scalar_fields/GoRawTypes/basic/types_gen.go

Correctly generate `bytes` scalar type in Go

---

internal/jennies/golang/jennies.go
internal/jennies/golang/runtime.go

Add an option to disable runtime-related codegen in Go

---

config/compiler/kind_registry.yaml
config/veneers/dashboard.common.yaml

Remove a few snapshot builder options

---

docs/releasing-grafana-foundation-sdk.md
scripts/release-all.sh

A bit of quality-of-life improvement :)

Add a script to release all supported grafana versions to the foundation-sdk

---

config/compiler/alerting.yaml
config/foundation_sdk.dev.yaml
config/foundation_sdk.yaml

Port fixes from Grafonnet to here.

fix(alerting): MatchType and TimeIntervalItem

---

Makefile
cmd/cog-config-schemas/main.go
config/compiler/alerting.yaml
config/compiler/common_passes.yaml
config/compiler/expr_passes.yaml
config/compiler/kind_registry.yaml
config/compiler/prometheus.yaml
config/compiler/testdata_passes.yaml
config/foundation_sdk.dev.yaml
config/foundation_sdk.yaml
config/veneers/accesspolicy.common.yaml
config/veneers/alerting.common.yaml
config/veneers/alerting.go.yaml
config/veneers/alerting.typescript.yaml
config/veneers/cloudwatch.go.yaml
config/veneers/dashboard.common.yaml
config/veneers/dashboard.go.yaml
config/veneers/dashboard.python.yaml
config/veneers/dashboard.variables.common.yaml
config/veneers/expr.common.yaml
config/veneers/folder.common.yaml
config/veneers/heatmap.common.yaml
config/veneers/prometheus.yaml
config/veneers/team.common.yaml
config/veneers/tempo.go.yaml
go.mod
go.sum
schemas/compiler_passes.json
schemas/pipeline.json
schemas/veneers.json

For basic autocomplete in IDEs.

First pass at generating schemas for cog's config

---

internal/codegen/run.go

Do not generate builders IR if builder generation is disabled

---

internal/jennies/golang/tools.go

Add more values to the list of reserved go keywords

---

internal/ast/compiler/disjunctions.go
internal/jsonschema/generator.go
internal/openapi/generator.go
internal/simplecue/generator.go

To ensure that struct fields are created in a consistent way.

Use constructor functions to create struct fields

---

config/foundation_sdk.dev.yaml
config/foundation_sdk.yaml
config/veneers/dashboard.python.yaml
internal/codegen/cue.go
internal/codegen/input.go
internal/codegen/jsonschema.go
internal/codegen/openapi.go
schemas/pipeline.json

Related: https://raintank-corp.slack.com/archives/C018SLDD5MW/p1718104998658489
It adds `DashboardMeta` schema.

Add DashboardMeta schema

---

internal/jennies/java/rawtypes.go
internal/jennies/java/templates/types/assigments.tmpl
internal/jennies/java/tmpl.go
internal/jennies/java/types.go
testdata/jennies/builders/constructor_initializations/JavaBuilders/constructor_initializations/SomePanel.java

It sets the correct enum value when it needs it.

Java: Fix constant assignments

---

.github/workflows/ci.yaml

It adds a small compile check for Java.

Java: Compile Java code in CI

---

internal/jennies/java/templates/veneers/assigment_Dashboard_WithPanel.tmpl

It initialises all gridPos values to avoid NPE trying to access to them.

Java: Initialise all gridPos values

---

schemas/pipeline.json

It updates the pipeline with the new information.

Schemas: Update pipeline schema

---

tsconfig.json

Note: similar changes will likely be needed in foundation-sdk

Fix Typescript CI steps

---

internal/jennies/php/rawtypes.go
internal/tools/maps.go

This will help with flaky diffs on PRs.

Deterministic output for disjunction encoding/decoding in PHP

---

internal/jennies/python/rawtypes.go

This will help with flaky diffs on PRs.
Similar to #543

Deterministic output for disjunction decoding in python

---

repository_templates/java/.github/workflows/java-release.yaml
repository_templates/python/.github/workflows/python-release.yaml
repository_templates/typescript/.github/workflows/typescript-release.yaml
scripts/release-version.sh

Always trigger a release in foundation-sdk when a package file is modified

---

.github/workflows/ci.yaml
.github/workflows/grafana-foundation-sdk-diff-preview.yaml
.gitignore
Makefile
README.md
devbox.d/php/php-fpm.conf
devbox.d/php/php.ini
devbox.json
devbox.lock

To ensure a consistent experience when working on cog, this PR introduces devbox as a way of providing the tools required by cog.

Set up devbox for a consistent dev/CI environment

---

internal/jennies/golang/converter_test.go
testdata/generated/cog/variants/variants.go
testdata/jennies/builders/array_append/GoConverter/sandbox/somestruct_converter_gen.go
testdata/jennies/builders/basic_struct/GoConverter/basic_struct/somestruct_converter_gen.go
testdata/jennies/builders/basic_struct_defaults/GoConverter/basic_struct_defaults/somestruct_converter_gen.go
testdata/jennies/builders/builder_delegation/GoConverter/builder_delegation/dashboard_converter_gen.go
testdata/jennies/builders/builder_delegation/GoConverter/builder_delegation/dashboardlink_converter_gen.go
testdata/jennies/builders/composable_slot/GoConverter/composable_slot/lokibuilder_converter_gen.go
testdata/jennies/builders/constant_assignment/GoConverter/sandbox/somestruct_converter_gen.go
testdata/jennies/builders/constraints/GoConverter/constraints/somestruct_converter_gen.go
testdata/jennies/builders/constructor_argument/GoConverter/sandbox/somestruct_converter_gen.go
testdata/jennies/builders/constructor_initializations/GoConverter/constructor_initializations/somepanel_converter_gen.go
testdata/jennies/builders/dataquery_variant_builder/GoConverter/dataquery_variant_builder/lokibuilder_converter_gen.go
testdata/jennies/builders/envelope_assignment/GoConverter/sandbox/dashboard_converter_gen.go
testdata/jennies/builders/foreign_builder/GoConverter/builder_pkg/somenicebuilder_converter_gen.go
testdata/jennies/builders/initialization_safeguards/GoConverter/initialization_safeguards/somepanel_converter_gen.go
testdata/jennies/builders/known_any/GoConverter/known_any/somestruct_converter_gen.go
testdata/jennies/builders/nullable_map_assignment/GoConverter/nullable_map_assignment/somestruct_converter_gen.go
testdata/jennies/builders/package-with-dashes/GoConverter/builderpkg/somenicebuilder_converter_gen.go
testdata/jennies/builders/panel_builders/GoConverter/panelbuilder/panel_converter_gen.go
testdata/jennies/builders/properties/GoConverter/properties/somestruct_converter_gen.go
testdata/jennies/builders/references/GoConverter/some_pkg/person_converter_gen.go
testdata/jennies/builders/struct_fields_as_args_assignment/GoConverter/sandbox/somestruct_converter_gen.go
testdata/jennies/builders/struct_with_defaults/GoConverter/struct_with_defaults/nestedstruct_converter_gen.go
testdata/jennies/builders/struct_with_defaults/GoConverter/struct_with_defaults/struct_converter_gen.go

Follow up to #566
Contributes to #314
This PR generates the golden files used to test the Go converter jenny.

Generate golden files for the Go converter jenny

---

package_templates/go/README.md
package_templates/java/README.md
package_templates/php/README.md
package_templates/python/README.md
package_templates/typescript/README.md

To match the one in the main READMEs

Update the maturity statement in Foundation SDK languages READMEs

---

internal/jennies/php/builder.go
internal/jennies/php/converter.go
internal/jennies/php/rawtypes.go
internal/jennies/php/tmpl.go
internal/jennies/php/tools.go

A bit of simplification on how template helpers are managed in PHP. Less work for the jennies, and a single place to look at for helpers.

Simplify template helpers management in PHP

---

internal/jennies/golang/templates/runtime/runtime.tmpl
internal/jennies/golang/templates/runtime/variant_models.tmpl
testdata/generated/cog/runtime.go
testdata/generated/cog/variants/variants.go

This PR fixes a couple of bugs and issues found while converting dashboards from our Ops instance to Go.

Converter robustness in Go

---

internal/jennies/php/runtime.go
internal/jennies/php/templates/runtime/runtime.tmpl
internal/jennies/php/templates/runtime/unknown_dataquery.tmpl
internal/jennies/php/templates/runtime/unknown_dataquery_builder.tmpl

Helps when the type of a query can't be determined.

Convert "UnknownDataquery" to PHP

---

config/foundation_sdk.yaml

Let's ship it, and keep iterating on them :ship:

Publish the Go & PHP converters to the foundation-sdk

---

internal/openapi/generator.go
testdata/openapi/datatypes/GenerateAST/ir.json
testdata/openapi/datatypes/schema.json
testdata/openapi/split_schema/GenerateAST/ir.json

Correctly extract comments from object fields in OpenAPI schemas

---

.golangci.yaml
schema_transformations_test.go
types_from_cue_value_test.go

These examples will show up in the packages Go doc.

Add a couple of examples showing how to use the helper functions

---

repository_templates/php/.github/workflows/php-ci.yaml

To match what we use via devbox

Use more specific versions of phpstan and psalm in the Foundation SDK PHP CI

---

config/compiler/kind_registry.yaml
config/veneers/dashboard.variables.common.yaml
internal/ast/builder.go
internal/jennies/java/templates/types/constraints.tmpl

Fixes grafana/grafana-foundation-sdk#379
Note: these fields are defined in the Dashboard schema v2, just not on the current ones :(

Add a few missing fields on `dashboard.VariableModel`

---

config/veneers/dashboard.variables.common.yaml
internal/ast/types.go
internal/jennies/golang/builder.go
internal/jennies/golang/templates/builders/assignment.tmpl
internal/jennies/golang/tmpl.go
internal/jennies/golang/tools.go
internal/jennies/golang/types.go
internal/jennies/java/builders.go
internal/jennies/java/types.go
internal/jennies/php/templates/converters/converter.tmpl
internal/jennies/php/types.go
internal/jennies/python/types.go
internal/jennies/typescript/types.go
internal/tools/types.go

Relates to grafana/grafana-foundation-sdk#391
Took a bit more effort than it should since enum values were not always correctly formatted in constructor assignments.

Hidden constant variables

---

config/foundation_sdk.dev.yaml
internal/jennies/common/apireference.go

These badges will help identifying the content of a package, and answering questions such as "which panels are supported?" or "which queries are supported?"

Add badges to packages in API reference

---

.github/workflows/ci.yaml
.github/workflows/grafana-foundation-sdk-diff-preview.yaml
.github/workflows/release.yaml

It only sets the SHA for every action.

Github: Set specific version to actions

---

internal/ast/compiler/prefix_object_names_test.go
internal/ast/compiler/prefix_objects_names.go

Also add prefix to enum member names in PrefixObjectNames compiler pass

---

docs/compiler_passes.md
internal/veneers/option/actions.go
internal/veneers/option/rules.go
internal/yaml/option.go
schemas/veneers.json

This PR defines a new veneer to add comments to existing options

Define an "AddComments" option veneer

---

internal/jennies/common/templatehelpers.go
internal/jennies/golang/tmpl.go
internal/jennies/php/tmpl.go
internal/jennies/python/apiref.go
internal/jennies/python/builder.go
internal/jennies/python/builder_test.go
internal/jennies/python/jennies.go
internal/jennies/python/rawtypes.go
internal/jennies/python/rawtypes_test.go
internal/jennies/python/templates/builders/assignment.tmpl
internal/jennies/python/tmpl.go
internal/jennies/python/tools.go
internal/jennies/python/types.go
internal/jsonschema/generator.go
testdata/jennies/rawtypes/variant_dataquery/PythonRawTypes/models/variant_dataquery.py
testdata/jennies/rawtypes/variant_panelcfg_full/PythonRawTypes/models/variant_panelcfg_full.py
testdata/jennies/rawtypes/variant_panelcfg_only_options/PythonRawTypes/models/variant_panelcfg_only_options.py

Part of #705
Similar to #689 and #703, but for Python

Python - Remove schema-specific codegen

---

internal/codegen/cue.go

This should help conflicts that could arise when using cog within a working directory that already has a cue module defined (ie: grafana/grafana)

Try and force cue to consume all the schemas/module definitions from the vfs

---

.github/workflows/docs.yaml
.github/workflows/release.yaml

Publish documentation on tags push + on demand.

Split docs publishing out of the release pipeline

---

internal/jennies/php/tmpl.go
internal/jennies/python/rawtypes.go
internal/jennies/python/tmpl.go

Fix unmarshalling of maps in Python

---

internal/ast/compiler/prefix_objects_names.go
internal/ast/compiler/visitor.go

Add missing ConstantReference in visitor and update prefix compiler pass.

Add missing visitor for ConstantRefs and update prefix pass

---

internal/simplecue/generator.go

Explore referenced objects before defining constant references
